### ISSUE TITLE
Process doesn't close - OSX 

### ISSUE THREAD

**Issue by joaquinrinaudo-olx** [libgdx/packr#101]
Hello,

When running packr to embed an application on OSX, the process doesn't end properly as it does it Linux and it ends up hanging after the JVM is destroyed message is displayed. Is there any workaround for this?

Best regards,
Joaquín

**Comment by joaquinrinaudo-olx** [comment]
Hello,

Any update/proress here?

Best regards

**Comment by joaquinrinaudo-olx** [comment]
@code-disaster Hello Daniel, sorry to keep pinging but it would be nice if you could look over this one?

**Comment by code-disaster** [comment]
Hi,

not much I can say without further information. There would be more complaints if it'd be outright broken on OS X. Two ideas:

- Try a different JRE, if you didn't do so already.
- Make sure you exit the Java application gracefully. System.exit() does **not** apply as "graceful" in this context. E.g. if you use libGDX and the LWJGL2 backend, the default behaviour is to use System.exit(), see LwjglApplicationConfiguration.forceExit. The native application loop of OS X isn't very happy about such bailouts.
