### ISSUE TITLE
 ManagementFactory.getRuntimeMXBean() crashes VM without any information on what might be the problem

### ISSUE THREAD

**Issue by vertazzar** [libgdx/packr#102]
```Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
  # -XX:ErrorFile=/Users/admin/hs_err_pid%p.log
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Invoking static io.app.run.Main.main() function ...
configure loging...
23:22:01 DEBUG Main            :: configured logging...
Destroyed Java VM ...
```

no writes to the log file, nothing... i discovered that was the cause when I manually ``System.out.println()`` each init phase of the main()

If there is no way to avoid this error, please advise on how I can retrieve the Process ID. Thanks

EDIT: tried these jdks: ``openjdk-1.7.0-u45-unofficial-icedtea-2.4.3-macosx-x86_64-image.zip`` and ``openjdk-1.7.0-u80-unofficial-macosx-x86_64-image.zip``

**Comment by xoppa** [comment]
See: https://github.com/libgdx/libgdx/wiki/Issue-Tracker. Please use the forum or irc for personal support requests.

If you do think that there is an issue with libgdx, then please provide the information required as you were requested when opening this issue, see also: https://github.com/libgdx/libgdx/wiki/More-Info.

**Comment by vertazzar** [comment]
i avoided this problem by listing all processes using https://github.com/profesorfalken/jProcesses and checking if the process is running with the same command arguments

**Comment by vertazzar** [comment]
I haven't touched this in years now. I'm pretty sure if you download latest JVM somewhere it will start working
