### ISSUE TITLE
Can not Run CLI Application on Windows

### ISSUE THREAD

**Issue by nakkaya** [libgdx/packr#104]
I am trying to package my compiler [1] for all major platforms. It is written in Clojure and currently distributed as a single jar [2]. For Mac OS X and Linux packr works like a charm, on Windows however there problems with the packaging.

  - Executable gives an error saying `msvcr100.dll` is missing (on a clean Windows 8 install) following other issues copying `jre/bin/msvcr100.dll` to the top folder containing the exe file fixes this issue.
  -  Running `ferret.exe` using `cmd.exe` has no effect it does not run the app executable runs but as far as i can tell does not launch JVM because no compiler output is shown, however running `ferret.exe --cli --console --verbose` (as suggested by another issue) runs in a separate  window does produce the correct output but just disappears before I can take look at the output. 

I am using the latest version of packr [3] with the following JVM image [4] (I tried other images but same result.) You can see my build script in [5] starting on line 7231.

[1] http://ferret-lang.org/
[2] http://ferret-lang.org/builds/ferret.jar
[3] http://ferret-lang.org/build-artifacts/packr.jar
[4] http://ferret-lang.org/build-artifacts/openjdk-1.7.0-u80-unofficial-windows-amd64-image.zip
[5] https://raw.githubusercontent.com/nakkaya/ferret/master/ferret.org

**Comment by code-disaster** [comment]
Clojure is a black box for me. No idea why it would work on Linux and Mac OS, but fail on Windows. Maybe you find some hints here: https://github.com/libgdx/packr/issues/33#issuecomment-63168279

**Comment by karlsabo** [comment]
Packr has been updated to better search for Microsoft redistributable runtime DLL files. Please try the latest version of Packr.
