### ISSUE TITLE
Stuck on Creating Java VM ...

### ISSUE THREAD

**Issue by mstrelex** [libgdx/packr#107]
Hi,

My app on a Linux box where everything worked fine is now stuck on 
`"Creating Java VM ..."`
Nothing changed - I just rebooted it. Bundled java itself works fine if I launch the app using `.../jre/bin/java -jar myapp.jar`

Any ideas ?

Thanks.

**Comment by mstrelex** [comment]
It doesn’t print anything even if you wait 10 minutes.
When you press Enter (or any key) it prints:
[1]+  Segmentation fault      (core dumped)

**Comment by karlsabo** [comment]
If you're still using Packr, please try the latest snapshot (3.0.0-SNAPSHOT) and let me know if this is still an issue. I'll be closing this issue in a few weeks if I don't hear from you.

**Comment by mstrelex** [comment]
@karlsabo Will do, thanks.

**Comment by karlsabo** [comment]
@mstrelex are you still having this issue w/ the latest version of packr? If not I'd like to close this issue.
