### ISSUE TITLE
Segmentation fault when launching packaged project on Ubuntu 16.04

### ISSUE THREAD

**Issue by russnes** [libgdx/packr#108]
I successfully created a packaged libgdx game with packr, but when I launch the executable (on ubuntu 16.04) it crashes and outputs in the command line:

Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Segmentation fault (core dumped)

It does however work on another linux machine I have running Linux mint 17, and it does work on Windows 10. 
One thing I can come to think of is that I have openjdk-8 installed on the ubuntu 16.04 machine, and I'm packaging openjdk-7 with the app from https://github.com/alexkasko/openjdk-unofficial-builds. 

On the linux mint machine I have openjdk-7 installed and on the windows 10 I have no jre installed.

I downloaded the newest packr from the link on the github page today.

Is it possible that that is causing some kind of inconsistency?
Is there any way to output more information?

**Comment by SolarLune** [comment]
Hello! 

I'm also getting this issue - segmentation fault on Solus OS (64-bit Linux distro, fully updated). I can run the game `.jar` using my computer's JDK, and I can also run the game using my target JDK (using the `java` executable in `jre/bin/`). So, I can only guess that this is a packr-specific issue, specifically to do with the generated executable.

**Comment by vishwaraj00** [comment]
Any solutions to this issue?

**Comment by SolarLune** [comment]
I never found a solution, either, but I ended up making a Python script that does something like this. I have to clean it up and simplify it for general use, but the general idea is that it writes out batch files that load the JAR using a packaged JRE. The batch files aren't executables, of course, but it seems to work OK for general game / app distribution nonetheless.

It also can strip out parts of the JRE that aren't used (a simple process that just deletes the specified files, and directories), and copy files that you want to include to the target folder for each platform. You can _also_ specify arguments to run the JRE with, which is nice if you want to, say, constrict your JVM execution process to limit the garbage collection size.

**Comment by karlsabo** [comment]
If any of you are still using Packr, please try the latest snapshot and let me know if it's still an issue. I'll be closing this ticket in a few weeks if no one replies.
