### ISSUE TITLE
Version 2.0 is missing from Maven Central

### ISSUE THREAD

**Issue by njlr** [libgdx/packr#110]
I cannot find version 2.0 on Maven: 

[https://mvnrepository.com/artifact/com.badlogicgames.packr/packr](https://mvnrepository.com/artifact/com.badlogicgames.packr/packr)

**Comment by fleskesvor** [comment]
I hope this gets fixed soon. For now, I've just installed it into Maven locally.

**Comment by code-disaster** [comment]
If you don't want to build/install them yourself, 2.0-SNAPSHOT builds are made available at https://oss.sonatype.org/content/repositories/snapshots.

**Comment by vromero** [comment]
I'm confused, the documentation mention `<version>2.0</version>` but 2.0 seems to be only `2.0-SNAPSHOT`?

**Comment by karlsabo** [comment]
The read me document is updated with the latest information for obtaining Packr.  The latest versions are currently unavailable on oss.sonatype.org. (Maven Central).
