### ISSUE TITLE
jre can't be found when setting --cwd=$(pwd)

### ISSUE THREAD

**Issue by nikhedonia** [libgdx/packr#111]
After packing my java app with:
```bash
java -jar packr.jar \
    --platform linux64  \
    --jdk JDK_PATH \
    --executable buckaroo.bin \
    --mainclass com.loopperfect.buckaroo.Main \
    --classpath buckaroo.jar \
    --vmargs XstartOnFirstThread \
    --output linux
```

I discovered that the working directory is always path to the executable.
calling `buckaroo.bin -c --cwd=$(pwd) --config=$pathToConfig` causes the following error:

```
jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory
Error: failed to load VM runtime library!
```

What is the proper way of packing my application in order to make use of the working directory ?

**Comment by nikhedonia** [comment]
Looks like packr changes directory before loading all files:

https://github.com/libgdx/packr/blob/master/src/main/native/packr/src/packr.cpp#L394

configJson : 

https://github.com/libgdx/packr/blob/ef4035e392d36abce5fbdae0d67f4c25d4f5be18/src/main/native/packr/src/packr.cpp#L401

libJVM.so :

https://github.com/libgdx/packr/blob/ef4035e392d36abce5fbdae0d67f4c25d4f5be18/src/main/native/packr/src/linux/packr_linux.cpp#L44

A possible solution would be to change directory after everything has been loaded or use absolute paths using the executable path.

Would be helpful if someone could explain how to build the packr.jar so I can test it and make a PR.

**Comment by code-disaster** [comment]
- I don't quite understand what you are trying to do. How does your folder structure look like?
- The command line must be "enabled" by using "--cli" or "-c" as the very first argument, so `-c --cwd=$(pwd) --config=$pathToConfig` in your example.
- The build instructions are explained [here](https://github.com/libgdx/packr#building-from-source-code).

**Comment by nikhedonia** [comment]
My folder structure is unchanged:
my `/usr/lib/buckaroo/` contains:
- buckaroo.bin
- config.json
- buckaroo.jar
- jre/

I have a script in /usr/bin/buckaroo that calls buckaroo.bin and forwards all the cli args and prepends 
`-c --cwd=$(pwd) --config=/usr/lib/buckaroo/config.json`

**Comment by code-disaster** [comment]
Hm, ok. Why not treat /usr/lib/buckaroo/ as the working directory?

Please excuse my ignorance of Linux file system / install folder conventions, but I'm used to outright ignore everything /usr/bin & co, and keep everything together in one place. For example, with Steam as the primary distribution platform everything is installed at some arbitrary location anyway.

**Comment by nikhedonia** [comment]
As a Package Manager, Buckaroo manipulates the working directory by adding, removing and modifying the files. 
Imagine you would change the working directory of commands like `ls` or `pwd` - it would render them useless.

**Comment by karlsabo** [comment]
If you're still interested in this functionality, all the code is built with Gradle. You need a Java 8+ JDK, and a supported [native toolchain](https://docs.gradle.org/current/userguide/native_software.html#native-binaries:tool-chain-support).

**Comment by nikhedonia** [comment]
We don't use packr anymore as we moved to F#
