### ISSUE TITLE
Request adding NvOptimusEnablement and AmdPowerXpressRequestHighPerformance for Windows

### ISSUE THREAD

**Issue by someguy233** [libgdx/packr#114]
For windows binary, to support Intel + Dedicated gpu configurations on laptop, suggest to add the following exports: NvOptimusEnablement and AmdPowerXpressRequestHighPerformance.

[https://stackoverflow.com/questions/17458803/amd-equivalent-to-nvoptimusenablement](url)

**Comment by code-disaster** [comment]
Done in d7c4ca09aa609b6468df0eca7ce9b1875c681e7c
