### ISSUE TITLE
Executable generated with packr 'silently' exits

### ISSUE THREAD

**Issue by TrDiGa** [libgdx/packr#115]
Hello all,

When I run a windows generated executable with verbose and console, I get the message bellow printed out but then the VM is closed at the next line (variable assignation)

```
public class Main { 
	public static void main(String[] args) {
		System.out.println("Starting");
		Global.variable = true;

```

The Global class is in the same package as the Main class.

I'm successfully using launch4j with the same jar but I need a linux option.

Here's my config :
```
{
    "platform": "windows32",
    "jdk": "openjdk-1.7.0-u80-unofficial-windows-i586-image.zip",
    "executable": "LastSalvo",
    "classpath": [
        "LastSalvo.jar"
    ],
    "mainclass": "com.ickylevel.prepare.Main",
    "vmargs": [
       "Xmx1G"
    ],
    "resources": [
		"images",
		"maps",
		"shaders",
		"skin",
		"sounds"
    ],
    "minimizejre": "soft",
    "output": "out-win"
}
```

**Comment by Tharkius** [comment]
I'm facing this issue as well, but in my case I can't even get the executable to print info in the command-line, making it hard to debug.

I've tried invoking the exe from the command-line with "myapp -c -v", but the program just exits, printing nothing. I've also tried with "narsil -c -v --console" and the result is a new window spawning and closing right after.

My build.config:

> {
>   "platform": "windows64",
>   "jdk": "C:/Program Files/ojdkbuild/OpenJDK 8u161 (x86_64)",
>   "executable": "MyApp",
>   "classpath": [
>     "out/artifacts/MyApp/MyApp.jar"
>   ],
>   "mainclass": "com.tharkiusworks.Main",
>   "vmargs": [
>     "Xmx1G"
>   ],
>   "resources": [
>     "out/artifacts/MyApp/licenses",
>    "out/artifacts/MyApp/LICENSE.md",
>     "out/artifacts/MyApp/NOTICE.txt"
>   ],
>   "output": "out/win64"
> }

**Comment by karlsabo** [comment]
It's not clear to me what the output of the packr launcher is when you pass `-c --verbose`?

**Comment by karlsabo** [comment]
Closing from lack of activity.
