### ISSUE TITLE
Packr does not work with spring-boot fatjar

### ISSUE THREAD

**Issue by jrosiek** [libgdx/packr#116]
The issue appears because fat-jar is repackaged with compression. The entrypoint main class provided by spring-boot works only if the outer jar is uncompressed - otherwise it cannot map/access inner jars.

It would be great if we could mark which classpath entries should not be repackaged by Packr

**Comment by florianschmitt** [comment]
In case anyone else is stuck with this: Its possible to just unzip the spring-boot jar and change the mainClass of the packr config to `org.springframework.boot.loader.JarLauncher`.

After packr generated the folder go to the output folder and unzip the jar (and delete it afterwards). If you set the mainClass of the packr config to the Spring JarLauncher it should work. 

[Spring Documentation](https://docs.spring.io/spring-boot/docs/current/reference/html/executable-jar.html#executable-jar-exploded-archives)

**Comment by karlsabo** [comment]
Are you passing `removelibs` to your spring-boot jar? That's the only way packr will repackage the jar. I'd recommend not running `removelibs`.

**Comment by karlsabo** [comment]
Closing from lack of activity.

**Comment by thanosa75** [comment]
Just to further clarify here :- fat jar of Spring Boot will work just if mainClass is set to value `org.springframework.boot.loader.JarLauncher` - no unzip/delete is needed.
