### ISSUE TITLE
Missing Zulu JDK Support

### ISSUE THREAD

**Issue by napperley** [libgdx/packr#121]
With Packr it doesn't recognise the [Zulu JDK](https://www.azul.com/downloads/zulu/). There are a number of problems with Packr's JDK support:

1. Only Zip files are supported yet both Zulu and OpenJDK use the **tar.gz** file format
2. Java 9 and above isn't supported
3. No JRE is detected by Packr with the Zulu JDK (after converting the tar.gz file to a Zip file)

Using the following software:

- Kotlin 1.2.41
- Zulu JDK 10.0.0 (via SDK Man)
- Gradle 4.7 (using official Kotlin DSL)
- Packr 2.0-SNAPSHOT (via unofficial Maven repo)

Note that Packr is being pointed to Zulu JDK 10.0.1 (manually downloaded) for use with app packaging.

## main.kt

```kotlin
package org.example.packr_example

import com.badlogicgames.packr.Packr
import com.badlogicgames.packr.PackrConfig
import java.io.File

fun main(args: Array<String>) {
    if ("--package-app" in args) packageApp()
    else println("Hello World! :)")
}

private fun packageApp() {
    val packrConfig = PackrConfig().apply {
        platform = PackrConfig.Platform.Linux64
        jdk = "${System.getProperty("user.home")}/zulu10.1+11-jdk10-linux_x64.zip"
        executable = "packr_example"
        classpath = listOf("build/libs/packr_example-0.1-SNAPSHOT.jar")
        mainClass = "org.example.packr_example.MainKt"
        minimizeJre = "soft"
        outDir = File("linux_dist")
        vmArgs = emptyList()
    }

    Packr().pack(packrConfig)
}
```

## build.gradle.kts

```kotlin
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.internal.HasConvention
import org.jetbrains.kotlin.gradle.plugin.KotlinSourceSet
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

group = "org.example"
version = "0.1-SNAPSHOT"

buildscript {
    extra["shadow-ver"] = "2.0.1"

    repositories {
        mavenCentral()
        jcenter()
    }

    dependencies {
        classpath("com.github.jengelman.gradle.plugins:shadow:${extra["shadow-ver"]}")
    }
}

repositories {
    mavenCentral()
    jcenter()
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}

apply {
    plugin("com.github.johnrengelman.shadow")
}

plugins {
    kotlin(module = "jvm") version "1.2.41"
    application
}

application.mainClassName = "org.example.packr_example.MainKt"

dependencies {
    val kotlinVer = "1.2.41"
    val packrVer = "2.0-SNAPSHOT"

    compile(kotlin("stdlib-jdk8", kotlinVer))
    compile("com.badlogicgames.packr:packr:$packrVer")
}

val compileKotlin by tasks.getting(KotlinCompile::class) {
    kotlinOptions.jvmTarget = "1.8"
}
val shadowJar by tasks.getting(ShadowJar::class) {
    baseName = "packr_example"
    version = "0.1-SNAPSHOT"
    classifier = ""
    manifest {
        attributes["Main-Class"] = application.mainClassName
    }
}

task<Exec>("packageApp") {
    val jarPath = "$buildDir/libs/${shadowJar.baseName}-${shadowJar.version}.jar"
    val command = "${System.getProperty("java.home")}/bin/java"

    dependsOn(shadowJar)
    commandLine(command, "-jar", jarPath, "--package-app")
    doFirst {
        file("$projectDir/linux_dist").deleteRecursively()
    }
}
```

## settings.gradle.kts

```kotlin
rootProject.name = "packr-example"
```

**Comment by code-disaster** [comment]
> Only Zip files are supported yet both Zulu and OpenJDK use the tar.gz file format

Contributions welcome. In our projects, I tend to just download, decompress and repack to .zip, then point the packr build to this local copy.

> Java 9 and above isn't supported
> No JRE is detected by Packr with the Zulu JDK (after converting the tar.gz file to a Zip file)

This is because nobody so far tried to add support.

In my opinion, Java 9+ and jlink render a big portion of packr obsolete. Plus they changed the folder layout again, so it probably would need some changes to the native executable too. I also expect issues with JNI and the changes done to class loaders.

I'm not sure it would be worth the effort to maintain a version supporting all of that while remaining compatible to Java 7/8.

**Comment by napperley** [comment]
Still think that there is a compelling use case for software projects that don't use [JPMS](http://tutorials.jenkov.com/java/modules.html) (Java Platform Module System) and require JRE 9 and above. The **jlink** tool doesn't cater for software projects that don't use JPMS, which leaves a void that hasn't been filled (the **javapackager** tool covers this only if **JRE 8** is used). Jlink requires a software project to be a **Explicit** module (even includes all dependencies), **NOT** a **Automatic** module (pre JVM 9).

**Comment by karlsabo** [comment]
Your three mentioned issues have been resolved. I do recommend using `jlink` to create your JRE as packr won't minimize Java 9+. See the updated README for more information.
