### ISSUE TITLE
Executable contain disallowed architectures i386, how to fix?

### ISSUE THREAD

**Issue by vminc** [libgdx/packr#122]
Got an error when submitting app to mac store:
ERROR ITMS-90240: "Unsupported Architectures. Your executable contained the following disallowed architectures: '[i386 ... ". New apps submitted to the Mac App Store must support 64-bit starting January 2018, and Mac app updates and existing apps must support 64-bit starting June 2018."

How do I exclude i386 architecture from the executable generated by packr?

**Comment by code-disaster** [comment]
Oh, looks like Apple means business this time.

Historically, the packr executable has been compiled as an "universal/fat binary" supporting both 32 and 64 bit. Apparently the App Store detects and faults with the 32-bit part.

I pushed a change which removes the 32-bit binary.
