### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by l7ssha** [libgdx/packr#124]
Download link just returns 404 Not Found

EDIT: That link [https://libgdx.badlogicgames.com/packr/packr.jar](https://libgdx.badlogicgames.com/packr/packr.jar)

![image](https://user-images.githubusercontent.com/23033957/40599568-0d9ddf80-624e-11e8-8f95-26ecc2ef973d.png)

**Comment by prakis** [comment]
Came here to say this. Please let me know if you figureout other means of getting the jar.

Thank you

**Comment by prakis** [comment]
Its very easy to build jar file from source, let me know if you need help.

**Comment by jpaszek** [comment]
You can also download the jar from the maven repository: https://mvnrepository.com/artifact/com.bladecoder.packr/packr/2.1

**Comment by prakis** [comment]
Thank you @jpaszek

**Comment by ruffiely** [comment]
Thank you @jpaszek Problem still exists! :)

**Comment by code-disaster** [comment]
This bit.ly short-link still points to the outdated URL. Mario told me there's a redirect in place, but this doesn't seem to work. I changed it to the "real" URL for now.

Also, the Maven dependency now points to the Sonatype snapshot repository. I don't know who's responsible for this com.bladecoder release version.
