### ISSUE TITLE
[RFE] Inline console on Windows

### ISSUE THREAD

**Issue by nedtwigg** [libgdx/packr#125]
It would be great if there was a way for the `.exe` to automatically send stdout and stderr to the console, rather than needing to do `myapp.exe -c > output.txt 2>&1` to get from file, or `myapp.exe -c --console` for a popup.  This change might be a lot of work, but it would be great to know what the challenges are, where the code would need to be modified, etc.

**Comment by karlsabo** [comment]
Hey Ned, I can't remember if you helped me with this on my fork or not, anyways, this is now fixed. The packr launcher will attach to its parent processes console if there is one.
