### ISSUE TITLE
Crash on windows, but works for linux

### ISSUE THREAD

**Issue by egordorichev** [libgdx/packr#127]
Hello. 
I'm trying to build my app for windows and linux. For linux it works just fine, but on windows it crashes (tho launching just jar works fine). Launching the app on windows doesn't give any errors at all (even in my app logs), but just closes. When running on linux with wine it gives this:

```
wine ./out/windows64/burningknight.exe 
fixme:ver:GetCurrentPackageId (0x60f7d0 (nil)): stub
fixme:seh:RtlAddFunctionTable 0x8850170 1 8850000: stub
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000826edd6, pid=35, tid=0x0000000000000024
#
# JRE version:  (8.0_172-b01) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.172-b01 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x26edd6]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
# An error report file with more information is saved as:
# Z:\home\egor\Dungeon\dist\out\windows64\hs_err_pid35.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
fixme:msvcrt:__clean_type_info_names_internal (0x7a2630) stub
fixme:msvcrt:__clean_type_info_names_internal (0x755d20) stub
fixme:msvcrt:__clean_type_info_names_internal (0x18000b670) stub
fixme:msvcrt:__clean_type_info_names_internal (0x87cf030) stub
```

Not sure if jvm bug is something, that can be fixed, but is there any work around? I'm using openjdk 8, if something.

Thanks, Egor.

**Update:**

Accembled an empty app using libgdx project setup, with default code and stuff. It runs fine on both os, but packing for windows still results the same issue.

**Comment by egordorichev** [comment]
Got it working with openjdk 7. But it's a tmp solution for me, cause it limits me to using old version of kotlin, lwjgl2 backend of libgdx, and other. That's pretty sad, and I still hope to get openjdk8 working.

**Comment by Nufflee** [comment]
cc @badlogic @code-disaster

**Comment by code-disaster** [comment]
Can't reproduce, works fine here with Zulu JDK 1.8.0_172-b01 (64-bit).

Any useful output if you run with `--cli --console --verbose`?

**Comment by Nufflee** [comment]
@code-disaster  We got it working with Zulu JDK 162 for 64-bit and Zulu 172 for 32-bit on Windows. I guess that 172 would work for 64-bit too but it still crashes with Wine (he tried all JDK's). You'll have to wait for @egordorichev to get more info about Wine crash.

**Comment by egordorichev** [comment]
Well, we can't always trust wine, that was my fail. Super sorry for that. Once @Nufflee on a normal windows machine tried some other JDKs, they worked just fine.
