### ISSUE TITLE
./demo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./demo)

### ISSUE THREAD

**Issue by ebremer** [libgdx/packr#136]
I've used packr successfully on Windows.  The packr command works fine on CentOS7, however, when I run the produced executable, I get the following error:

./demo: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./demo)

**Comment by wefahakem** [comment]
@ebremer I'm having the same problem running it on red Hat. Did u resolve it?

**Comment by karlsabo** [comment]
Please try the latest version of packr and update this issue if it's still an issue.

**Comment by karlsabo** [comment]
Closing because of no response.
