### ISSUE TITLE
using jre packaged by jlink

### ISSUE THREAD

**Issue by brunesto** [libgdx/packr#137]
I use jlink to produce a trimmed version of the jre, which I would like to use with packr
The problem is that  jlink places libjvm.so on the path  jre/lib/server/libjvm.so

But packr_linux.cpp expects the jvm to be inside a specific folder 
"jre/lib/amd64/server/libjvm.so"

On linux this is not much of a problem as I can add a symbolic link, but how to solve this on windows?
If there is no workaround please could you add a parameter for specifying the path to the libjvm.so and dll ?
Thanks

**Comment by AAbhishek1234** [comment]
Just a question , From where are you downloading the OpenJDk for linux and macOS ? I cant seem to find any good one .

**Comment by brunesto** [comment]
I downloaded it from https://jdk.java.net/

**Comment by karlsabo** [comment]
A recent merge should resolve this issue.
