### ISSUE TITLE
What exactly is packr looking for (Couldn't find JRE in JDK) v2

### ISSUE THREAD

**Issue by lamba92** [libgdx/packr#141]
I am reopening [this](https://github.com/libgdx/packr/issues/129). That's a very simple but frustrating problem :-/

**Comment by vanDarg** [comment]
Running into the same issue, I saw that in Packr.java method _searchJre()_ (line 290) explicitely looks for a directory named "jre". I got around this issue by opening my zipped JRE and renaming the root folder in there to just that, "jre". After that, it worked.

**Comment by karlsabo** [comment]
Please try the latest version of packr, the JRE search method has been updated to support newer Java versions.

**Comment by touhidurrr** [comment]
> Please try the latest version of packr, the JRE search method has been updated to support newer Java versions.

Tried but doesn't work

**Comment by karlsabo** [comment]
@touhidurrr, please open a new issue with details on your problem.
