### ISSUE TITLE
Will this work for Java 11, which doesn't come with JRE?

### ISSUE THREAD

**Issue by yccheok** [libgdx/packr#142]
Hi,

May I know will `packr` will work with Java app (Developed using Swing, JavaFX) for Java 11? As, Java 11 seems doesn't come with JRE anymore.

**Comment by karlsabo** [comment]
Some OpenJDK distributions still package a JRE. However, packr has been updated to support Java up to Java 14. The `--minimizejre` feature won't do much for Java 9+, it's recommended to use `jlink` to create your JRE. The test project, <https://github.com/libgdx/packr/tree/master/TestAppJreDist>, contains build script code for creating a jlink JRE and using it with packr.
