### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by wholder** [libgdx/packr#144]
Trying to run `packr` using this command line (all needed files in the current directory), like this:

`java -jar packr.jar --platform mac --jdk ./openjdk-1.7.0-u80-unofficial-macosx-x86_64-bundle.zip --executable MyApp --classpath ./MyApp.jar --removelibs ./MyApp.jar --mainclass MyApp --vmargs Xmx1G --minimizejre soft --output mac `

Produces this response:
```
Cleaning output directory '/Users/wholder/Desktop/Builder/mac' ...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 7
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at com.badlogicgames.packr.Packr.buildMacBundle(Packr.java:101)
	at com.badlogicgames.packr.Packr.pack(Packr.java:63)
	at com.badlogicgames.packr.Packr.main(Packr.java:360)
```

Which is not much to go on.  Any ideas what I'm doing wrong?

Note: running on MacPro with macOS Mojave 10.14.2 and using openjdk version "11.0.2" 2019-01-15 to run `packr`.

Wayne

**Comment by wholder** [comment]
The code throwing the exception is in the Packr class:

`values.put("${bundleIdentifier}", this.config.mainClass.substring(0, this.config.mainClass.lastIndexOf('.')));`

In particular, the  subexpression "`this.config.mainClass.lastIndexOf('.')`" is the problem.

Ok.  I figured out that I need to write

  `--mainclass MyApp.class`

not:

`--mainclass MyApp`

To make it work.  However, it seems to me like the code could produce an error message for this.

Wayne

**Comment by karlsabo** [comment]
I'm guessing it was more of an oversight, it's unusual to use the default package. You could pass `--bundle my.bundle.id` to workaround the issue.
