### ISSUE TITLE
Unable to run jar created with jruby

### ISSUE THREAD

**Issue by amo13** [libgdx/packr#146]
I created a jar with jruby (using shoes4) which runs perfectly fine when invoking with `java -jar myapp.jar`. But when I use packr to create an executable (linux64) and launch the executable, I get the following error output on my terminal:
```
LoadError: no such file to load -- META-INF/init
  require at org/jruby/RubyKernel.java:984
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:59
   <main> at <script>:2
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- META-INF/init
```
To me, it looks like (j)ruby can't find the init.rb file inside the META-INF folder of my jar. 
My packr configuration looks like this:
```
{
    "platform": "linux64",
    "jdk": "jdk-8u212-ojdkbuild-linux-x64.zip",
    "executable": "MyApp",
    "classpath": [
        "myapp.jar"
    ],
    "removelibs": [
        "myapp.jar"
    ],
    "mainclass": "JarMain",
    "vmargs": [
       "Xmx1G"
    ],
    "output": "out-linux64"
}
```

Do you have an idea what goes wrong? Did I miss something?

**Comment by karlsabo** [comment]
The option `removelibs` extracts the jar, removes shared libraries that don't match the target platform and then creates a new jar. During the jar creation process it isn't respecting the meta-inf directory.
Do you need removelibs to preserve meta-inf?

**Comment by karlsabo** [comment]
Closing because of no response.
