### ISSUE TITLE
build for Mac

### ISSUE THREAD

**Issue by mikej1688** [libgdx/packr#151]
Both has jre issue, 

packr examples ask zip for JDK. I downloaded jdk-8u221-linux-i586.tar.zg and jre-8u221-macosx-x64.tar.gz from Oracle. I converted both to zip. 

Run json to get issues:  

For Mac:
Downloaded jre-8u221-macosx-x64.tar, then converted it to zip. The structure of zip is: 
   jre-8u221-macosx-x64.zip -> jre1.8.0_221.jre (folder) -> Contents  -> Home (folder), MacOS (folder), info.plist. Home has jre contents like bin, lib, etc. 

Got error message: 
   java.io.IOException: Couldn't find JRE in JDK, see 'C:\docs\packr\out-mac\Contents\Resources\tmp'

Can someone help for a clue?

**Comment by idontusenumbers** [comment]
I worked around the issue by decompressing the tar, renaming `Home` to `jre`, compressing the `jre` folder to `jre.zip` and passing that as the JRE

**Comment by mikej1688** [comment]
> I worked around the issue by decompressing the tar, renaming `Home` to `jre`, compressing the `jre` folder to `jre.zip` and passing that as the JRE

It's good. thank you.
