### ISSUE TITLE
Upgrade from Java 11 to Java 12 fails to launch on MacOS due to libjli.dylib not found.

### ISSUE THREAD

**Issue by nadernader99** [libgdx/packr#152]
After upgrading from openjdk 11.0.2 to openjdk 12.0.2, the generated executable for MacOS will not launch.  Running the executable from a terminal displays the following error message prior to exit:
```
dlopen(jre/lib/jli/libjli.dylib, 1): image not found
Error: failed to load VM runtime library!
```

In openjdk 12.0.2, the location of this dynamic library was moved from jre/lib/jli/libjli.dylib to jre/lib/libjli.dylib.  The jli subdirectory no longer exists.

The root cause appears to be the following line in packr_macos.cpp.  

https://github.com/libgdx/packr/blob/96c609388fb011589acbddd18c9d3d2f77e32806/src/main/native/packr/src/macos/packr_macos.cpp#L113

Manually creating the jli subdirectory and then adding a symbolic link libjli.dylib -> ../libjli.dylib in the jre is a temporary workaround to this issue.  However, attempting to create the symbolic link within the target jre prior to running packr caused packr to fail while copying the jre.   What works is to create the symbolic link within the packr generated output <appname>.app/Contents/Resources/jre prior to running pkgbuild to create the installer.

**Comment by karlsabo** [comment]
OpenJDK moved the location of the libjli.dylib shared library. Recent merges to packr have resolved this issue, please try the latest packr release.

**Comment by nadernader99** [comment]
Fix confirmed.  The symbolic link work-around was removed and package was built using packr-all-2.7.0.jar.  The application launched successfully.  Thank you.
