### ISSUE TITLE
Builded exe doesn't run (openJDK11 and JavaFX11)

### ISSUE THREAD

**Issue by tomaszkyc** [libgdx/packr#153]
Hi there,

I can't run my builded app. After clicking on .exe file nothing happens but process is run ( found in Task Manager ).

I use Amazon Correto JDK 11 for Windows: [link](https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html)

and JavaFX 11: [link](https://gluonhq.com/products/javafx/)

Config: 

```
{
    "platform": "windows64",
    "jdk": "C:\\Program Files\\Amazon Corretto\\jdk11.0.4_10",
    "executable": "my-simple-app",
    "classpath": [
        "my-simple-app-1.5.jar",
        "C:\\dev\\java\\library\\javafx-sdk-11.0.2\\lib",
        "C:\\dev\\java\\library\\javafx-sdk-11.0.2\\bin"
    ],
    "mainclass": "my.simple.app.MainApp",
    "vmargs": [
        "---module-path lib",
        "---add-modules javafx.controls,javafx.fxml"
    ],
    "output": "my-simple-app-out-win"
}
```

After build command: 

```
java -jar packr.jar config.json
```

and enter the build folder: 

```
cd my-simple-app-out-win
```

I can run the jar with command: 

```
java --module-path .\lib\ --add-modules javafx.controls,javafx.fxml -jar .\my-simple-app-1.5.jar
```

but running exe doesn't work.

Please help :)

**Comment by karlsabo** [comment]
The latest versions of Java moved some shared libraries around. This issue was resolved with some recent merges. Please try the latest version of packr.
