### ISSUE TITLE
The compressed JRE not working for old java 8 versions(8u45)

### ISSUE THREAD

**Issue by AAbhishek1234** [libgdx/packr#155]
I was compressing ojdk version 201 which is mentioned in Packr github . Due to incompatibility between 8u60+ versions and Intel Sandy bridge processors I have to downgrade to 8u45 , I downloaded the jdk from oracle and ran packr on it but the extracted jre is unable to start my windows application . Error : jvm.dll is missing cannot run application . !! Need help .

**Comment by karlsabo** [comment]
Hey @AAbhishek1234, can you try the latest version of packr and see if you run into any issues?

**Comment by karlsabo** [comment]
Closing because there was no response.
