### ISSUE TITLE
MacOS: app doesn't run if signed with hardened runtime enabled

### ISSUE THREAD

**Issue by devLotto** [libgdx/packr#157]
As of macOS Catalina, apps signed with a new Developer ID need to have the hardened runtime enabled to run as per https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution.

If the app created by packr is signed with the hardened runtime enabled, the app will halt when running, producing this error:
```
dlopen(jre/lib/jli/libjli.dylib, 1): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
Error: failed to load VM runtime library!
```

**Comment by JoelOtter** [comment]
Hi, can I ask how you're signing a JVM application? When I tried this was only supported in newer JREs (11?) and packr doesn't support these.

**Comment by devLotto** [comment]
@JoelOtter

I use ``OpenJDK11U-jre_x64_mac_hotspot_11.0.4_11.tar.gz`` from https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.4+11 and it works fine with packr for me. 11.0.6+10 and the nightly version of 11 works fine too for me. JDK11+ doesn't contain the JRE anymore, so make sure to download the JRE and not the JDK.

The output .app from packr is signed using ``codesign`` from Xcode.

**Comment by JoelOtter** [comment]
Thank you! I shall use the branch from your PR (doesn't seem like things are getting merged here). Did you need to do anything special to get packr to support `.tar,gz`? I saw a couple of other PRs attempting to add that.

**Comment by JoelOtter** [comment]
@devLotto 

I managed to re-pack it myself to make Packr happy. Unfortunately the `codesign` incantation I'm using doesn't seem to work. I'm using:

```
codesign --force --options runtime --deep --sign "$DIST_CERT" --entitlements ../../../../buildTools/entitlement.plist Feud.app
```

Unfortunately the binaries inside the JRE don't seem to get signed. Would you be able to share the args you used? Thanks. :)

**Comment by devLotto** [comment]
@JoelOtter 

I haven’t signed the JRE binaries. At the time of making this issue, Apple didn’t require those binaries to be signed with the hardened runtime enabled. If you want to sign them I think you can run codesign multiple times, specifying the direct path to the various binaries. AdoptOpenJDK JRE 11.0.7 will allegedly be properly signed so you could also wait for that to be released.

**Comment by karlsabo** [comment]
Applying @devLotto libjli fix and adding the following entitlements resolved this for me:
com.apple.security.cs.allow-jit true
// Allow loading dylib files that aren't signed with the same certificate as the executable
com.apple.security.cs.disable-library-validation true
// Resolved java.lang.UnsatisfiedLinkError: Failed to locate library: libobjc.dylib
com.apple.security.cs.allow-dyld-environment-variables true

I built x86-64 version on my fork https://github.com/karlsabo/packr/releases if you want to use them.

cheers

**Comment by nedtwigg** [comment]
I have no relation to libgdx or karlsabo.  I stepped through all the changes in [karlsabo's fork](https://github.com/karlsabo/packr), and there's a lot of great improvements to various things, and best of all public CI running on win/mac/linux.  Packr is a great project, very happy to see an active fork with cross-platform CI.

**Comment by JoelOtter** [comment]
Thanks all. If this repo is indeed unmaintained we could try and build community consensus around which fork we contribute to - I would be happy to adopt @karlsabo's going forward :)

**Comment by karlsabo** [comment]
My fork has been merged into libgdx/packr. Hardened runtime is now working on macOS

**Comment by benjamin-heasly** [comment]
Years later, this thread helped me out!  I didn't find other sources mentioning `com.apple.security.cs.allow-dyld-environment-variables`, but setting this this flag seemed to be what I was missing.

**Comment by alexanderhenne** [comment]
@benjamin-heasly Is that the only flag you had to set? What Java version and are you using Adoptium Temurin or something else? Do you want to share the error you got if you didn't have that flag? For me `com.apple.security.cs.disable-library-validation` and `com.apple.security.cs.allow-jit` was enough so it would be interesting to know if `com.apple.security.cs.allow-dyld-environment-variables` is needed for something too.
