### ISSUE TITLE
Created .exe does nothing

### ISSUE THREAD

**Issue by jacek-bulatek** [libgdx/packr#162]
Hello,

I have similar symptoms to #33 , but when I run myApp.exe > win.log it creates empty file.
Here is my pacr-config.json:
```
{
    "platform": "windows64",
    "jdk": "https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u80-unofficial-linux-i586-image.zip",
    "executable": "myApp",
    "classpath": [
        "desktop/build/libs/desktop-1.0.jar"
    ],
    "mainclass": "com.xxx.desktop.DesktopLauncher",
    "vmargs": [
       "Xmx1G"
    ],
    "resources": [
        "core/assets"
    ],
    "minimizejre": "soft",
    "output": "bin/win64"
}
```
packr creates expected folder structure and found in there desktop-1.0.jar works fine.

I couldn't find openjdk 1.8 yet that is the version of compiler I am using (I use github actions and I can't find java.home in any help pages), so I guess that can lead to some errors in runtime, but so far no exact "runtime" has occured.

**Comment by jacek-bulatek** [comment]
I just found out that I didn't mention that I create my fat jar by invoking ```gradlew desktop:dist``` in my github action

**Comment by SakiiCode** [comment]
You are using a linux JDK for windows build and Java 7 is really outdated now
Try downloading proper OpenJDK 8 from this website: https://adoptopenjdk.net/releases.html

**Comment by jacek-bulatek** [comment]
It helped thanks!
