### ISSUE TITLE
Should be a warning or message in the documentation that the output directory cleans the directory.

### ISSUE THREAD

**Issue by Daburnell112** [libgdx/packr#169]
Upon running this for the first time I placed the output directory for the executable as my main project directory. It proceeded to try and delete all the files in the directory without warning. Fortunately I have a Git backup of everything but the metadata is all corrupted in my project now. It doesn't say anywhere in the readme that it will try to delete everything in the directory.

**Comment by crykn** [comment]
Hey @Daburnell112, that is very unfortunate to hear - our apologies. This issue was recently fixed with #167, but a new version of packr including the fix wasn't released yet.
