### ISSUE TITLE
Custom minimizejre config exception

### ISSUE THREAD

**Issue by TCreutzenberg** [libgdx/packr#170]
Hey there, first of all: Thanks so much for providing packr, it's really cool!

I have a LibGDX project, everything is running, packr works fine under normal conditions.
The desktop.jar generated by "gradle desktop:dist" works fine.
Maybe I'm doing something wrong here already:
- The desktop.jar already contains all my assets from the android/assets folder
- But when exceuting the packr-generated .exe the assets in the .jar are not found so I just copy all the assets manually in the packr-generated directory: Everything works fine then, the .exe starts and the game runs. Great!
- Now I actually want to remove the redundant assets from the desktop.jar using a custom minimizejre config "minimizeJRECustomConfig"
- The config is found by packr because it runs fine when I just specify "soft" (instead of my custom config "minimizeJRECustomConfig")
- My custom config is just the default "soft" config where I specified that the folder "music" should be removed from the desktop.jar (see below)
- My local java version which packr uses is: openjdk version "11.0.8" 2020-07-14, the game itself is packed and run with OpenJDK14U 

I start packr from the command line with:
```java
-jar [packr-all-2.7.0.jar]
--platform windows64
--jdk [OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.zip]
--useZgcIfSupportedOs
--executable tcgame
--classpath [desktop.jar]
--mainclass de.creutzenberg.desktop.DesktopLauncher
--vmargs Xmx1G
--minimizejre minimizeJRECustomConfig
--output [output directory]
```

"minimizeJRECustomConfig":
```{
  "reduce": [
    {
      "archive": "jre/lib/rt.jar",
      "paths": [
        "com/sun/corba",
        "com/sun/jndi",
        "com/sun/media",
        "com/sun/naming",
        "com/sun/rowset",
        "sun/applet",
        "sun/corba",
        "sun/management"
      ]
    },
    {
      "archive": "desktop-0.11.0.jar",
      "paths": [
        "config/config.data"
      ]
    }
  ],
  "remove": [
    {
      "platform": "*",
      "paths": [
        "jre/lib/rhino.jar"
      ]
    },
    {
      "platform": "windows",
      "paths": [
        "jre/bin/*.exe",
        "jre/bin/client"
      ]
    }
  ]
}
```

I'm getting this output in the console and the folder "music" is still in desktop.jar. Also, the .exe does not run any more.

```Cleaning output directory '[outputdirectory]' ...
Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
Didn't detect any compression for archive [OpenJDK14U-jdk_x64_windows_hotspot_14.0.2_12.zip]: No Compressor found for the stream signature.
Minimizing JRE ...
Didn't detect any compression for archive [desktop.jar]: No Compressor found for the stream signature.
java.nio.file.FileAlreadyExistsException: C:\Users\x\y\z\desktop\META-INF\INDEX.LIST
        at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:87)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:235)
        at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
        at java.base/java.nio.file.Files.newOutputStream(Files.java:219)
        at java.base/java.nio.file.Files.copy(Files.java:3066)
        at com.badlogicgames.packr.ArchiveUtils.extractArchive(ArchiveUtils.java:88)
        at com.badlogicgames.packr.PackrReduce.minimizeJre(PackrReduce.java:88)
        at com.badlogicgames.packr.Packr.copyAndMinimizeJRE(Packr.java:409)
        at com.badlogicgames.packr.Packr.pack(Packr.java:173)
        at com.badlogicgames.packr.Packr.main(Packr.java:73)
```

Thank you very much for your help and time in advance!

**Comment by karlsabo** [comment]
Please try the latest jar from [packages](https://github.com/libgdx/packr/packages/394128).

**Comment by TCreutzenberg** [comment]
Wow, that was quick, thanks! I'll try it tomorrow. Cheers! 😄

**Comment by TCreutzenberg** [comment]
Works, great! Thanks so much! 👍

**Comment by karlsabo** [comment]
No problem, thanks for testing.
