### ISSUE TITLE
Can't get codesign to work for MacOS

### ISSUE THREAD

**Issue by mschering** [libgdx/packr#172]
Hi All,

I;m struggling with signing my app for macOS. I have a Comodo Code signing certificate which should work for MacOS.

This is my packr.json:

```
{
    "platform": "mac",
    "jdk": "OpenJDK14U-jre_x64_mac_hotspot_14.0.2_12.tar.gz",
    "executable": "Group-Office Assistant",
    "classpath": [
        "../../target/groupoffice-assistant-1-jar-with-dependencies.jar"
    ],
    "removelibs": [
    ],
    "mainclass": "com.intermesh.groupoffice.assistant.GOA",
    "vmargs": [
    ],
    "resources": [
    ],
    "icon": "GroupOffice.icns",
    "output": "dist/Group-Office Assistant.app"
}

```

After running packr I run (entitlements.plist contains the content show in the readme of this repo):

`codesign --options=runtime --verbose=4 -s "Intermesh BV" --entitlements entitlements.plist dist/Group-Office\ Assistant.app`

Output:

`dist/Group-Office Assistant.app: signed app bundle with Mach-O universal (x86_64) [com.intermesh.groupoffice.assistant]
`

Then I verify it which works:
`codesign --verbose=4 dist/Group-Office\ Assistant.app
`
Output:
`dist/Group-Office Assistant.app: valid on disk
`
But this command fails:
`spctl --verbose=4 --assess --type execute dist/Group-Office\ Assistant.app
`
Output:
`dist/Group-Office Assistant.app: rejected
`

I hope someone can help me out!

Thanks.

Best regards,
Merijn

**Comment by karlsabo** [comment]
Hey Merijn, notarization is a pain. Here's some information that might help:

You need to use the `--deep` option to sign an app bundle, which is not recommended.

I've provided examples at <https://github.com/libgdx/packr#example-macos-code-signing-and-notarization-command-line-steps>. These steps include everything you need to code sign, notarize, staple and check the status of your notarization.

**Comment by mschering** [comment]
Hi,
I already tried --deep but that also failed. I was also afraid that it would resign the already signed jre that I bundle. I didn't use the xcrun command yet. I also don't have an Apple Developer account. I thought I could use my Comodo certificate for this purpose as well or can't I?

**Comment by mschering** [comment]
I think it doesn't work without a cert from apple. I just read this note:

https://comodosslstore.com/resources/macos-codesign-how-do-i-sign-a-file-with-code-signing-certificate-in-macos/

**Comment by karlsabo** [comment]
I've never tried code signing on macOS using a non Apple cert. You cannot notarize without an Apple developer account and notarized is what's needed for apps to run on Catalina (10.15+). So I'm not sure it's worth trying a non Apple certificate. Unless your only goal is to sign.

**Comment by karlsabo** [comment]
@mschering Were you able to get code signing and notarization working? If so I'd like to close this issue.

**Comment by mschering** [comment]
Yes please close it. I think it worked but macOS only accepts apple certificates. I will try this later.
