### ISSUE TITLE
Support Side-by-side Binaries

### ISSUE THREAD

**Issue by joshuaskelly** [libgdx/packr#174]
It would be nice to have packr built binaries live side by side. In my case I'd love to have a _game.exe_ and _editor.exe_ in the same directory using the same runtime.

**Comment by karlsabo** [comment]
Hey Joshua, this would be a nice feature to have. It should be pretty straight forward to add and I'm only fixing bugs and small issues on the project. Pull requests are more than welcome.

If you're using a later version of Java you should look into [jpackage](https://docs.oracle.com/en/java/javase/15/docs/specs/man/jpackage.html) it might satisfy all your requirements for a packager and installer.

**Comment by petoncle** [comment]
@karlsabo What was your idea for this? 
The problem I see is that both launchers are going to read from the same `config.json` file. And so we'd probably want one config.json per app? Maybe we could make the packr launcher read something like `config-<appname>.json` where `<appname>` is the file name of the launcher. 
With OP's examples, that would be `config-game.json` and `config-editor.json`. But that's a breaking change.

**Comment by karlsabo** [comment]
@petoncle, that's what I was thinking too, <app name>[.exe] then have a matching <app name>.json.

I can change the version to 4.0 in-case anyone out there is reading the config.json file themselves or tries to drop new executables in place without running packr-all.

**Comment by karlsabo** [comment]
This enhancement is available in a snapshot release:

I pulled locally and my CI published your changes:
https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr-all/3.1.0-SNAPSHOT/
packr-all-3.1.0-20210221.221700-10.jar 21-Feb-2021 22:17 3.47 MB

I'll release 4.0 early next month. Thanks @petoncle for PRs!

**Comment by joshuaskelly** [comment]
![image](https://user-images.githubusercontent.com/372642/113341901-9f6e4400-92e2-11eb-9dfe-23e2712e37bb.png)

Works like a charm! Thank you so much for implementing this. ❤️
