### ISSUE TITLE
Creating relative path from path "error"?

### ISSUE THREAD

**Issue by wholder** [libgdx/packr#175]
Great program, but I'm confused by an "error" message I can't seem to fix.  My invocation is:

```
      PackrConfig config = new PackrConfig();
      config.platform = PackrConfig.Platform.MacOS;
      config.jdk = "NativeBuilder/resources/oracle/jre-8u271-macosx-x64.tar.gz";
      config.executable = "MyApp";
      config.classpath = Arrays.asList("out/artifacts/MyApp_jar/MyApp.jar");
      config.removePlatformLibs = config.classpath;
      config.mainClass = "MyApp";
      config.vmArgs = Arrays.asList("Xmx1G");
      config.minimizeJre = "soft";
      config.outDir = new java.io.File("NativeBuilder/macos/MyAppMac64.app");
      config.useZgcIfSupportedOs = true;
      config.verbose = true;
      new Packr().pack(config);

```

and this seems to produce a workable output file.  However, it also spits out some 20,000 lines of text that look like this:

`18:06:01.557 [main] ERROR com.badlogicgames.packr.ArchiveUtils - Creating relative path from path=NativeBuilder/macos/MyAppMac64.app/Contents/Resources/MyApp.jar.tmp/TestEditorWithTooltips.class, rootDirectory=NativeBuilder/macos/MyAppMac64.app/Contents/Resources/MyApp.jar.tmp, relativePathString=TestEditorWithTooltips.class
`

Any idea what I'm doing wrong?  This is running in an IntelliJ project using Java 1.8.-_271 on macOs Mojave.

Wayne

**Comment by karlsabo** [comment]
Looks like a "debug" log I left on as an error 😳. I'll take a look and confirm it later when I'm at my computer.

**Comment by karlsabo** [comment]
Thanks for the issue, this will be fixed in the next patch or release.

**Comment by wholder** [comment]
Thanks.  Is there any way I can shut off the messages until the next
release is out?

Wayne

**Comment by karlsabo** [comment]
Yes, you can set a system property to configure the logger, <https://logging.apache.org/log4j/2.x/manual/configuration.html#AutomaticConfiguration>.

**Comment by wholder** [comment]
Thanks.  Much appreciated.

Wayne
