### ISSUE TITLE
Could not initialize class java.awt.Toolkit 

### ISSUE THREAD

**Issue by WinterAlexander** [libgdx/packr#178]
When running the following command `.\Jumpai.exe --cli --console --verbose` I get:

```
Changing working directory to C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows ...
Loading JVM runtime library ...
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\jre\bin
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\jre\bin\server
Passing VM options ...
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
isZgcSupported()=1, hasJsonValue(jsonRoot, "useZgcIfSupportedOs", sajson::TYPE_TRUE)=0
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
Passing VM options:
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # Jumpai.data
Invoking static net.jumpai.client.desktop.DesktopLauncher.main() function ...
Checked for an exception from the main method, exceptionOccurred=1
Calling java.lang.Thread#dispatchUncaughtException(Throwable) on main thread
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.desktop/java.awt.Component.<clinit>(Component.java:621)
        at net.jumpai.client.desktop.DesktopLauncher.main(DesktopLauncher.java:34)
Destroyed Java VM ...
Press ENTER key to exit.
```

I'm using AdoptOpenJDK 11 LTS with hotspot

My packr config is the following

```
{
    "platform": "windows64",
    "jdk": "out/jdks/win64-jdk",
    "executable": "Jumpai",
    "classpath": [
        "desktop/build/libs/Jumpai.data"
    ],
    "removelibs": [
        "desktop/build/libs/Jumpai.data"
    ],
    "mainclass": "net.jumpai.client.desktop.DesktopLauncher",
    "minimizejre": "none",
    "output": "out/packr/win64"
}
```

(I'm not minimizing the JRE).

This error is only happening on a fresh Windows 10 installation. On my old Windows 7, everything works fine. If I instead launch the game using `.\jre\bin\java.exe -jar Jumpai.data`, everything works fine. (This is using the JRE that was output by packr).

Any idea? Does packr gets rid of `java.awt` despite minimizejre being unspecified? If so, how come it works when using the same JRE and not the .exe?

**Comment by karlsabo** [comment]
I'm not sure why it would fail on Windows 10. Have you tried without using removelibs? Maybe it's breaking the JAR.

**Comment by karlsabo** [comment]
Looked at the code, remove `"minimizejre": "none",`. The code doesn't check the value and so it's minimizing the JRE.

**Comment by WinterAlexander** [comment]
> Looked at the code, remove `"minimizejre": "none",`. The code doesn't check the value in a robust way (checks != null) and so it's minimizing the JRE.

Thanks, will try again without this line and without removelibs.

**Comment by WinterAlexander** [comment]
@karlsabo Tried without the minimizejre and without the removelibs. Same behavior. I know it isn't the jar nor the jre since using powershell to run the jar with the same jre works perfectly.

**Comment by WinterAlexander** [comment]
When I look at the code of packr for windows, it seems jre/bin/client/jvm.dll is not added. (Only server). This might be the reason why java.awt.Toolkit is not present as it is probably a client only class. I struggle to recompile the native source though and simply copying the jvm.dll file in the main folder doesn't seem to resolve the issue.

**Comment by WinterAlexander** [comment]
I tested adding a line to search for dlls in `jre/bin/client`, no luck I still get the same thing:

```
Changing working directory to C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows ...
Loading JVM runtime library ...
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows\jre\bin
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows\jre\bin\server
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows\jre\bin\client
Passing VM options ...
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
isZgcSupported()=1, hasJsonValue(jsonRoot, "useZgcIfSupportedOs", sajson::TYPE_TRUE)=0
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
Passing VM options:
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # Jumpai.data
Invoking static net.jumpai.client.desktop.DesktopLauncher.main() function ...
Checked for an exception from the main method, exceptionOccurred=1
Calling java.lang.Thread#dispatchUncaughtException(Throwable) on main thread
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.desktop/java.awt.Component.<clinit>(Component.java:621)
        at net.jumpai.client.desktop.DesktopLauncher.main(DesktopLauncher.java:35)
Destroyed Java VM ...
Press ENTER key to exit.
```

Desperate at this point, maybe it's a name clash with the server's one?

**Comment by karlsabo** [comment]
I noticed earlier you said you're using AdoptOpenJdk 11, are you passing the JRE or the JDK to packr? AOJ JDK archives don't have a "jre" folder in them anymore, so those won't work with packr.

If you're making your own JRE using jlink, make sure you're passing `--add-modules java.desktop`, otherwise make sure you're passing packr a JRE, not a JDK 9+. E.g., https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jre_x64_windows_hotspot_11.0.9.1_1.zip

Starting with Java 9 (I think) they removed the "jre" folder from JDKs.

**Comment by WinterAlexander** [comment]
@karlsabo I was indeed using the jdk. Now I switched to jre and I have the exact same problem:

```
Changing working directory to C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows ...
Loading JVM runtime library ...
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows\jre\bin
Added DLL search directory C:\Users\Winter\Desktop\Jumpai-0.0.0-Windows\Jumpai-0.0.0-Windows\jre\bin\server
Passing VM options ...
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
isZgcSupported()=1, hasJsonValue(jsonRoot, "useZgcIfSupportedOs", sajson::TYPE_TRUE)=0
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
Passing VM options:
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # Jumpai.data
Invoking static net.jumpai.client.desktop.DesktopLauncher.main() function ...
Checked for an exception from the main method, exceptionOccurred=1
Calling java.lang.Thread#dispatchUncaughtException(Throwable) on main thread
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.desktop/java.awt.Component.<clinit>(Unknown Source)
        at net.jumpai.client.desktop.DesktopLauncher.main(DesktopLauncher.java:35)
Destroyed Java VM ...
Press ENTER key to exit.
```

Again, using the ` .\jre\bin\java.exe -jar .\Jumpai.data` command works well.

I am not yet using jlink. The jre given to packr is exactly what is downloaded from Adopt Open JDK. (Now using the latest 11 JRE).

**Comment by WinterAlexander** [comment]
@karlsabo Do you have a working AdoptJDK 11 jre example project I can test on my fresh windows 10?

**Comment by karlsabo** [comment]
Yes, the Gradle project `PackrAllTestApp` runs tests using Adopt 8, 11, and 15. See PackrAllTestApp/packrAllTestApp.gradle.kts.

Locally I added a JFrame to `com.badlogicgames.packrtestapp.PackrAllTestApplication#main`
```java
                  JFrame myFrame = new JFrame("Hello");
		  myFrame.getContentPane().add(new JLabel("Hello world!"));
		  myFrame.pack();
		  myFrame.setLocationRelativeTo(null);
		  myFrame.setVisible(true);

		  Thread.sleep(5_000);
		  myFrame.setVisible(false);
		  myFrame.dispose();
```

The tests ran with no issue and the JFrames popped up for me.

**Comment by karlsabo** [comment]
Tests for Java 11, and 15 use jlink created JREs, so you also have to add
```kotlin
args("--add-modules")
args("java.desktop")
```

to TestAppJreDist/testAppJreDist.gradle.kts

**Comment by WinterAlexander** [comment]
@karlsabo can I export those tests to run them on the fresh machine too? I highly suspect it would start working it I simply installed some jdk. It works on my regular windows 7. The problem is that it's not working on a 100% fresh installed machine.

**Comment by WinterAlexander** [comment]
I added the lines you mentionned and created my JFrame test, but gradle is unable to apply the plugin `org.gradle.cpp-application`

```
6:21:34 p.m.: Executing task 'createTestDirectory'...

> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
Configuration on demand is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Build file '/home/winter/Packr/PackrLauncher/packrLauncher.gradle.kts' line: 27

* What went wrong:
An exception occurred applying plugin request [id: 'org.gradle.cpp-application']
> Failed to apply plugin 'org.gradle.cpp-application'.
   > Project#afterEvaluate(Action) on project ':PackrLauncher' cannot be executed in the current context.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 182ms
6:21:34 p.m.: Task execution finished 'createTestDirectory'.
```

Any clue on this one?

**Comment by karlsabo** [comment]
No clue, what's outputted when you run `gradlew --version`? Maybe Gradle wrapper isn't running the correct version, or it's picking up the wrong Java version.

**Comment by WinterAlexander** [comment]
```
------------------------------------------------------------
Gradle 6.6.1
------------------------------------------------------------

Build time:   2020-08-25 16:29:12 UTC
Revision:     f2d1fb54a951d8b11d25748e4711bec8d128d7e3

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.10 (Oracle Corporation 11.0.10+8)
OS:           Linux 5.10.6-arch1-1 amd64

``

That's the version setup in build.gradle

**Comment by karlsabo** [comment]
`OS:           Linux 5.10.6-arch1-1 amd64`

I thought you were on Windows 10...

**Comment by karlsabo** [comment]
That output looks good for Linux, I've only tested on Ubuntu 18.04 and 20.04, but I can't think of any reason it wouldn't work on arch linux

**Comment by WinterAlexander** [comment]
> `OS: Linux 5.10.6-arch1-1 amd64`
> 
> I thought you were on Windows 10...

I plan on testing on a **fresh** windows 10. I have an installation of windows 10 that is only for testing, I'm not installing anything on it. The point of building this test is to run it on the fresh win10.

I strongly doubt the problem is the fact I'm building on linux. I can reboot on my old windows 7 to build it there, but last time I tried I was unable to do gradle signing on there.

**Comment by karlsabo** [comment]
I was mostly concerned you were running from a WSL console. 

I've never seen that Gradle issue on Linux. I've only used Ubuntu which is what the packr project GitHub CI uses too. But there's no reason to think it's an OS issue. I didn't find anything with a quick Google search. 

 I can't reproduce any AWT issues on my Windows 10 with adopt 11 and packr. 

There's some Java 2d properties you could try fiddling with, but it doesn't make any sense that running jre/bin/java works but packr launcher doesn't.

**Comment by WinterAlexander** [comment]
@karlsabo Same story on windows 7:

```
Alexander Winter@PC-Alex MINGW64 ~/Desktop/packr (master)
$ ./gradlew PackrAllTestApp:createTestDirectory
Starting a Gradle Daemon, 3 incompatible and 3 stopped Daemons could not be reused, use --status for details

> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Alexander Winter\Desktop\packr\PackrLauncher\packrLauncher.gradle.kts' line: 27

* What went wrong:
An exception occurred applying plugin request [id: 'org.gradle.cpp-application']
> Failed to apply plugin 'org.gradle.cpp-application'.
   > Project#afterEvaluate(Action) on project ':PackrLauncher' cannot be executed in the current context.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 42s
```

This is from a fresh clone, I basically ran

```
git clone http://github.com/libgdx/packr
cd packr
./gradlew PackrAllTestApp:createTestDirectory
```

This issue might be bothersome but that's really not the actual issue. @karlsabo Can you just send me a zip of your test app so I can test it on my fresh windows 10?

**Comment by WinterAlexander** [comment]
> 
> I can't reproduce any AWT issues on my Windows 10 with adopt 11 and packr.
> 

Have you ever tried on a fresh installation that doesn't have anything installed on it? What I suspect since the beginning is that some dll needed by packr is not loaded by packr but is found anyway on any machine that has pretty much any version of java installed. This issue on linux is very similar and shows that `java.awt.Toolkit` is located in some library file: https://stackoverflow.com/q/18099614 I have no idea what this library is but I am determined to find out at this point.

**Comment by karlsabo** [comment]
It could be a DLL error, but I've only seen those present as UnsatisfiedLinkError exceptions.

Here's my App bundle that uses a JFrame:
<https://drive.google.com/file/d/1XpXKWxRj1y7Olh8qZdyajYFZ1jJEyapU/view?usp=sharing>

**Comment by WinterAlexander** [comment]
@karlsabo Interesting, now with your thing it finds the class but it fails to load another library!

```
Changing working directory to C:\Users\Winter\Desktop\OpenJDK11U-jlink-jre_x64_windows_hotspot_11 ...
Loading JVM runtime library ...
Added DLL search directory C:\Users\Winter\Desktop\OpenJDK11U-jlink-jre_x64_windows_hotspot_11\jre\bin
Added DLL search directory C:\Users\Winter\Desktop\OpenJDK11U-jlink-jre_x64_windows_hotspot_11\jre\bin\server
Passing VM options ...
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
isZgcSupported()=1, hasJsonValue(jsonRoot, "useZgcIfSupportedOs", sajson::TYPE_TRUE)=0
versionInformation.dwMajorVersion=10, versionInformation.dwMinorVersion=0, versionInformation.dwBuildNumber=19042
  # -Xms64M
  # -Xmx128M
  # -Dsun.java2d.noddraw=true
  # -XstartOnFirstThread
Passing VM options:
  -Xms64M
  -Xmx128M
  -Dsun.java2d.noddraw=true
  -XstartOnFirstThread
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 5 classpaths ...
  # PackrAllTestApp-3.1.0-SNAPSHOT.jar
  # log4j-slf4j-impl-2.13.1.jar
  # slf4j-api-1.7.30.jar
  # log4j-core-2.13.1.jar
  # log4j-api-2.13.1.jar
Invoking static com.badlogicgames.packrtestapp.PackrAllTestApplication.main() function ...
Hello world!
Running from java.version=11.0.9.1
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
Loaded resource line: My resource!
Checked for an exception from the main method, exceptionOccurred=1
Calling java.lang.Thread#dispatchUncaughtException(Throwable) on main thread
Received uncaught exception in thread.getName()=main, Thread.currentThread().getName()=main
java.lang.UnsatisfiedLinkError: C:\Users\Winter\Desktop\OpenJDK11U-jlink-jre_x64_windows_hotspot_11\jre\bin\awt.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1395)
        at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1393)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1392)
        at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1425)
        at java.desktop/java.awt.Component.<clinit>(Component.java:621)
        at com.badlogicgames.packrtestapp.PackrAllTestApplication.main(PackrAllTestApplication.java:56)
Destroyed Java VM ...
Press ENTER key to exit.
```

Should they even be considered to be different errors? Doesn't that mean that `java.awt.Toolkit` isn't in `awt.dll` if that's the one loading it? I am very curious how those errors could differ. I will try using jlink on a JDK just like you to see if that's the cause of the change.

As always before, using the `java -jar` works fine.

**Comment by WinterAlexander** [comment]
Looking at this: https://github.com/AdoptOpenJDK/openjdk-support/issues/135 it seems to be due to missing MSVC runtimes which are needed to load awt.dll and also present in the jre/bin folder. It fails to find them there but can possibly find them in some other places in a non fresh machine.

**Comment by karlsabo** [comment]
It could be having trouble loading the MSVCP140.dll from the jre/bin directory, it's supposed to be on the search path. `AddDllDirectory` is called with the full path, from the logs `Added DLL search directory C:\Users\Winter\Desktop\OpenJDK11U-jlink-jre_x64_windows_hotspot_11\jre\bin`.

Maybe you could try preemptively loading it from the packr code.

I'm also curious if you tried disabling DirectDraw, Direct3d and OpenGl to see what happens. <https://docs.oracle.com/javase/10/troubleshoot/java-2d-properties.htm#JSTGD585>
1. -Dsun.java2d.noddraw=true — Disable the use of the DirectDraw pipeline. GDI will be used instead.
2. -Dsun.java2d.d3d=false — Disable the use of the Direct3D pipeline.

**Comment by WinterAlexander** [comment]
@karlsabo OMG! Copying the msvcp140.dll in the base folder makes it work! Both for my game and your test. That's definitely it, this library is not properly loaded but found anyway in non fresh installation of windows.

I also tried every combination of the 2 options you gave me but it did not change the error.

I'm glad we found it! It's definitely a bug in the end. Unfortunately I don't have much experience with dll and library loading, so I'm not of much help for a code fix. I'll be shipping my game with this dll in the base folder for now though.

If you want to test out this behavior yourself, I highly recommend installing a fresh windows (virtual machine?) for this purpose. It's not the first time I have lots of windows dll issues and one thing is sure, a windows with software installed is radically different from a fresh installation in many ways.

**Comment by karlsabo** [comment]
Please try the latest SNAPSHOT <https://artifactory.nimblygames.com/artifactory/ng-public-snapshot/com/badlogicgames/packr/packr-all/3.0.2-SNAPSHOT/> (Currently packr-all-3.0.2-20210117.053514-4.jar  is the latest).

**Comment by WinterAlexander** [comment]
@karlsabo Works! :) At least for OpenJDK 11. I can try packing with OpenJDK 14 later. As for OpenJDK 8, my game needs Java 9 or later so I can't test it. I would need the TestApp to work which was quite bothersome.

If you want me to try those 2 jdks with zipped apps feel free to send them, this would take much less time for me.

Anyway I'm glad the main issue was fixed.

**Comment by karlsabo** [comment]
Awesome, thanks for verifying. Nah, that's okay I tested all 3 JREs. I test by uninstalling all the microsoft redistributable runtimes. Just never tested with AWT after my 3.0 change. ☹️

**Comment by karlsabo** [comment]
3.0.2 was published to releases.
