### ISSUE TITLE
Delete libs that do not match architecture?

### ISSUE THREAD

**Issue by WinterAlexander** [libgdx/packr#186]
We have a feature that removes the libs from platforms that are not matching (let's say linux from mac) but we keep 32 bit libs on 64 bit machines. Back in the day where packr still supported 32 bit machines, I wrote code to delete the libs with the wrong architecture: 

```
private static void removeArchitectureLib(PackrConfig config) throws IOException
{
	if (config.removePlatformLibs == null || config.removePlatformLibs.isEmpty())
		return;

	if(config.platform == Platform.MacOS)
		return;

	boolean is64 = config.platform.name().contains("64");

	System.out.println("Removing unrelated architecture platform libs ...");

	// let's remove any shared libs not used on the platform, e.g. libGDX/LWJGL natives
	for(String classpath : config.removePlatformLibs)
	{
		File jar = new File(config.outDir, new File(classpath).getName());
		File jarDir = new File(config.outDir, jar.getName() + ".tmp");

		if(config.verbose)
		{
			if(jar.isDirectory())
				System.out.println("  # JAR '" + jar.getName() + "' is a directory");
			else
				System.out.println("  # Unpacking '" + jar.getName() + "' ...");
		}

		if(!jar.isDirectory())
			ZipUtil.unpack(jar, jarDir);
		else
			jarDir = jar; // run in-place for directories


		File[] files = jarDir.listFiles();

		if(files != null)
			for(File file : files)
			{
				if(!isLib(file))
					continue;

				if(is64 && !file.getName().contains("64") || !is64 && file.getName().contains("64"))
				{
					if(config.verbose)
						System.out.println("  # Removing '" + file.getPath() + "'");

					deleteFile(file);
				}
			}

		if(!jar.isDirectory())
		{
			if(config.verbose)
				System.out.println("  # Repacking '" + jar.getName() + "' ...");

			long beforeLen = jar.length();

			deleteFile(jar);

			ZipUtil.pack(jarDir, jar);
			FileUtils.deleteDirectory(jarDir);

			long afterLen = jar.length();
			if(config.verbose)
				System.out.println("  # " + beforeLen / 1024 + " kb -> " + afterLen / 1024 + " kb");
		}
	}
}

private static boolean isLib(File file)
{
	String name = file.getName().toLowerCase(Locale.ENGLISH);

	return name.endsWith(".dll") || name.endsWith(".so") || name.endsWith("dylib");
}
```

Now, I know we no longer support 32 bit machines. But do deleting 32 bit library still a desired thing? Since not all 64 bit libraries might not have "64" in them, a option should be added to PackrConfig as well.

If this feature is desired, I can make a PR. Otherwise, I'll just keep it to myself.

**Comment by karlsabo** [comment]
I don't think this is needed anymore, libGDX and LWJGL package the native libraries in their own JAR. See <https://repo1.maven.org/maven2/com/badlogicgames/gdx/gdx-platform/1.9.13/>. The `removelibs` option is also destructive, I discourage its use as much as possible.

It would be a pretty minor addition to PackrReduce.java, so if you feel so inclined, I would review the PR, there might be some folks stuck on LWJGL 2 that would use it. To me, it doesn't seem worth saving ~4 megabytes.

**Comment by WinterAlexander** [comment]
Interesting, I'm indeed one of the people stuck in LWJGL 2. I originally did this to save space with the insane 100-115 MB library [humblevideo](https://github.com/artclarke/humble-video).

Out of curiosity, why is removelibs destructive? As far as I'm concerned, having the .so in windows doesn't have much of a purpose.

**Comment by WinterAlexander** [comment]
Anyway I'm closingthis since I got my answer. If anyone wants this change just ping me and I'll open a PR. Otherwise I won't since it won't work with the new way to do things in libGDX.
