### ISSUE TITLE
Trouble using Packr with Gradle

### ISSUE THREAD

**Issue by Badbloodyy** [libgdx/packr#187]
Hi ! Still new to Java and wanting to use libgdx, i've followed a guide to make a simple game on desktop. After doing so, i wanted to create an .exe and found your amazing tool.

Unfortunately i can't manage to add the jar to my project via gradle.
I've tried to add the dependencies with gradle but to no avail, here's what i've done and the following error.

![gradlepackr](https://user-images.githubusercontent.com/63103800/105189561-602eb480-5b35-11eb-933c-9420658d3408.png)

`org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'Drop'.
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method maven() for arguments [https://oss.sonatype.org/content/repositories/snapshots/] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.`

I thought it was the "implementation" and changed it to 'classpath' but it said that there was no repository for it, but it was a step forward. I can't manage to add the repository and i couldn't found the same error while searching for that issue.
I'm sorry to ask it here but i can't find a way to add Packr to my project.

I tried to add it manually but it said that there was an issue (not related to packr) with the android's part of the project (something about the asset already being somewhere else), and i can't fix it either.

Thanks for reading !

**Comment by karlsabo** [comment]
Hey,

I applaud your ambition, but I would recommend starting smaller and building your way up to such a large project.

1. Using copy paste with markdown code tags is much better than pasting screenshots. <https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code>
2. You're placing all your dependencies and repositories in the buildscript block, Gradle is beyond complicated, I would recommend going through the getting started tutorial <https://docs.gradle.org/current/userguide/getting_started.html>
3. It looks like you copy pasted from the read-me which uses [Kotlin](https://docs.gradle.org/current/userguide/kotlin_dsl.html) and your buildscript is written in Groovy.
   * I recommend using Kotlin, you get more help from the IDE,

**Comment by Badbloodyy** [comment]
I didn't even see that Gradle was using Groovy, well ^^'.

Thanks for the input and the different advices ! Kotlin seems future proof but i want to keep coding in Java and go to kotlin when i have more experience under my belt. I didn't manage to make it work for the moment, i will read the Gradle tutorial and try to figure out how to add these dependencies.

Have a good day !

**Comment by karlsabo** [comment]
Gradle build scripts can be written in Groovy or Kotlin. That's what I meant by I recommend Kotlin. 

Once you're more familiar with Gradle, there's source for a simple test app using packr that you could borrow build script source from. https://github.com/libgdx/packr/tree/master/PackrAllTestApp
