### ISSUE TITLE
You are not authorized to open the application

### ISSUE THREAD

**Issue by JesusBetaX** [libgdx/packr#190]
Hello and sorry for my English. 

I am trying to package a MacOS app. 

The app works fine with an administrator user, however when I open the app with a standard user it shows me this error: You are not authorized to open the application. 

First of all, Thanks

**Comment by JesusBetaX** [comment]
![16117870435287506239760218442276](https://user-images.githubusercontent.com/28900436/106063554-fb87d280-60bd-11eb-908d-cd23a0d506c9.jpg)

**Comment by JesusBetaX** [comment]
![16117871680456931063424492711613](https://user-images.githubusercontent.com/28900436/106063695-40136e00-60be-11eb-8e99-d0575a222580.jpg)

**Comment by JesusBetaX** [comment]
The funny thing is, if I just run the "".jar"" file it works

**Comment by JesusBetaX** [comment]
![Uploading 16117878524005718460836157157261.jpg…]()

**Comment by JesusBetaX** [comment]
![16117879089034612786494834154349](https://user-images.githubusercontent.com/28900436/106064793-f9bf0e80-60bf-11eb-9480-155e5b557de6.jpg)

**Comment by JesusBetaX** [comment]
Apparently it detects that if you add all the permissions to the file that is generate with the packaging. works

chmod 755 /MyApp/Contents/MacOS/MyApp

**Comment by karlsabo** [comment]
Thanks for letting us know how to resolved the issue.
