### ISSUE TITLE
regression in linux-x64 - undefined_symbol: pthread_once

### ISSUE THREAD

**Issue by nedtwigg** [libgdx/packr#192]
For Linux x64, I have long-used the [super-old May 2018 artifacts](https://github.com/libgdx/packr/tree/b2601f76bd4905f92c3e1ab6fefbf5a008c455f9/src/main/resources) from before heroic @karlsabo reinvigorated the project.

The new mac and windows [launchers in `3.0.2`](https://github.com/libgdx/packr/releases/tag/3.0.2) work fantastic, but I have a regression with the linux launcher:

```
./MyApp: symbol lookup error: /home/ned/.cache/JNA/temp/jna24266<long#>.tmp: undefined symbol: pthread_once
```

It could be specific to my app, I do use JNA. But if I just swap back to the old launcher with no other changes, then everything works fine. I'm in a happy state - the old linux launcher works great, and so do the new win and mac launchers. Happy to assist with providing debug info if that is helpful, or happy to continue as I am :)

**Comment by karlsabo** [comment]
Hey Ned,

It would be nice to figure it out, as far as I can tell none of the Packr launcher code for Linux uses pthread, though curiously it is compiled with the library `-lpthread`. Have you taken a look at PackrLauncher/packrLauncher.gradle.kts? I'm curious if anything in there stands out as wrong for compiling on Linux.

**Comment by nedtwigg** [comment]
I think it *might* be that `-lpthread` needs to come last.

So the `if` should be at the bottom, not the top. I'll take a whack at testing this hypothesis later today.

https://github.com/libgdx/packr/blob/06d78f472e038fcc46342e8cc87d6b34e517729f/PackrLauncher/packrLauncher.gradle.kts#L251-L256

**Comment by nedtwigg** [comment]
My comment above is wrong, but was the right direction. pthread was being added to the unit test, but was missing from the actual deployed artifacts. PR above fixes it for me.
