### ISSUE TITLE
Mac keeps throwing permission denied

### ISSUE THREAD

**Issue by crazzmc** [libgdx/packr#230]
It creates the package perfectly fine, when I change the folder to .app it just will not run at all. Permission denied in terminal

java -jar packr.jar --platform mac --executable Name --classpath JarName.jar --mainclass com.x.X --output launcher_mac --icon icon.icns --bundle com.x.X --jdk mac.zip

btw i am using OpenJDK11U-jdk_x64_mac_hotspot_11.0.18_10.tar.gz

**Comment by Frosty-J** [comment]
Did you fix this or give up on it? It may need the executable bit set like on Linux (on which `chmod +x ...`).
