### ISSUE TITLE
packr repo seems not to work

### ISSUE THREAD

**Issue by upost** [libgdx/packr#238]
Adding packr to my build.gradle does not work:

```
repositories {
        ...
        maven {
            url "https://artifactory.nimblygames.com/artifactory/ng-public"
            name 'Nimblygames'
        }
    }
...
dependencies {
        classpath 'com.badlogicgames.packr:packr:4.4.0'
}
```
The required URL [https://artifactory.nimblygames.com/artifactory/ng-public/com/badlogicgames/packr/packr/4.4.0/packr-4.4.0.pom](url) returns a 404.

https://central.sonatype.com/ only has outdated version.

Something wrong or is it just me?
Or is packr deprecated? In this case, maybe update the docs (and please add working sample for using jpackage, as I couldn't get that to work either)

**Comment by karlsabo** [comment]
I can't rebuild the release artifacts because the GPG key expired. You can download them from GitHub here: https://github.com/libgdx/packr/releases

You can also use a more recent version such as `4.1.0-SNAPSHOT` <https://artifactory.nimblygames.com/ui/native/ng-public/com/badlogicgames/packr/packr-all/>

**Comment by ia97lies** [comment]
I have packr included in my Jar. But Packr just vanished completely including the older version 3.0.3 on the artifactory.nimblygames. Any chance to bring it back on? Any plans to just push it on maven central?

**Comment by karlsabo** [comment]
I was unable to recover Artifactory after a version upgrade. I will try to rebuild and get artifacts published again. 

I don’t have permission to publish to maven central.

**Comment by karlsabo** [comment]
I was able to rebuild snapshot versions: https://artifactory.nimblygames.com/ui/native/ng-public/com/badlogicgames/packr/packr-all/

I can't rebuild the release versions because they use an old GPG key.

**Comment by karlsabo** [comment]
I was able to get the release builds built again, the repo now has the following versions:
- 3.0.3
- 4.0.0
- 4.0.1-SNAPSHOT
- 4.1.0-SNAPSHOT

**Comment by ia97lies** [comment]
Thank you so much for the fix, appreciate it!
