### ISSUE TITLE
DEB Installation Package Suggestion

### ISSUE THREAD

**Issue by naortega** [libgdx/packr#32]
Just as a suggestion, but for Linux (or more precisely anything Debian based like Ubuntu) maybe one could also choose between zip and deb packing. Deb package files are very common for most Linux distributions, and definitely most that gamers are going to use (mainly Ubuntu).

Again, just a suggestion. I may try to work on this myself as well.

**Comment by gouessej** [comment]
It is already possible with JNDT which is based on PackR and support both RPM and DEB packages:
https://gouessej.wordpress.com/2014/11/22/ardor3d-est-mort-vive-jogamps-ardor3d-continuation-ardor3d-is-dead-long-life-to-jogamps-ardor3d-continuation/#jndt

If you don't want to use my library (under GPL), you can still use PackR with jdeb. Good luck.

**Comment by karlsabo** [comment]
This is out of the scope of packr, but [jpackage](https://docs.oracle.com/en/java/javase/15/jpackage/packaging-overview.html#GUID-C1027043-587D-418D-8188-EF8F44A4C06A) creates installers.
