### ISSUE TITLE
Packr-generated exe prints nothing, does nothing

### ISSUE THREAD

**Issue by tommyettinger** [libgdx/packr#33]
I'm unsure what's causing this, but after running Packr with the command line

```
java -jar packr.jar -platform windows -jdk "C:/Users/user/.lein-packr-cache/windows.zip" -executable perlin -appjar "target/perlin-0.0.1-SNAPSHOT-standalone.jar" -mainclass "perlin/core/desktop_launcher" -minimizejre "hard" -resources resources -outdir out-win32
```

it successfully generates an exe in the directory out-win32.  Running this exe in the Windows 7 64-bit command prompt with no args causes nothing to be printed, and it immediately closes. Double clicking the exe causes the cursor on Windows 7 to show the spinning circle next to it for a few seconds, but opens no windows. What could cause this?

The JDK I'm using is from the recommended unofficial builds project [(zip file link)](https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u60-unofficial-windows-i586-image.zip). I can run the jar with `java -jar perlin-0.0.1-SNAPSHOT-standalone.jar` and it displays a libgdx window and renders some perlin noise.  This problem with the packed output happens whether -minimizejre is set or not, and I suspect it may be related to finding the main class, or to the structure of the unofficial build zips changing.  The demo is written in Clojure using the play-clj binding to libgdx, and I was able to run Packr 1.0 on Clojure apps before, so I suspect something broke in the meanwhile. I tried this with the latest Packr link available in the Readme, and programatically with the 1.2 version on Maven Central (more on that in a bit).  I did modify the soft and hard profiles as I mentioned in a comment on #18 . The non-working exe and working jar are bundled [here, with a jre from Packr](https://dl.dropboxusercontent.com/u/11914692/perlin.zip), so you can inspect it more closely.

I am also trying to make a plugin for the Clojure build tool called Leiningen, so it can use Packr to bundle JREs as part of a build step.  My code for this plugin (which is in Clojure, but very small right now) is available [on my Github](https://github.com/tommyettinger/lein-packr).  Generating anything programatically suffered the same fate as running Packr manually.

I'm at a loss for what to do here.  The output it generates is totally normal:

```
Unpacking JRE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
copying resources
minimizing JRE
unpacking rt.jar
packing rt.jar
Done!
```

But of course, it generates an exe that doesn't do anything.  Does anyone have an idea what could be wrong, and whether it's on my side or a bug with Packr?

**Comment by tommyettinger** [comment]
I'm still puzzled as to why Packr works for Java, but not for Clojure or Scala (I tried a jar built with each).  It initially worked with Clojure using an early version of Packr, before the change in [launcher.cpp](https://github.com/libgdx/packr/blob/master/native/src/launcher.cpp) to allow using long arguments to the JRE. I may be able to just downgrade to the earliest maven version of Packr and see if that does the trick.

**Comment by tommyettinger** [comment]
And downgrading to 1.1 works with Clojure but doesn't allow long VM args, and doesn't support 32-bit Linux... hm.  There's some problem introduced after 1.1...

**Comment by code-disaster** [comment]
I just did a quick setup on OS X:

- downloaded clojure-1.6.0.jar
- tried "java -cp clojure-1.6.0.jar clojure.main" to validate that it works

Then I ran different versions of packr using the following config:

```
{
   "jar": "clojure-1.6.0.jar",
   "mainClass": "clojure.main",
   "vmArgs": [
      "-Xmx1G"
   ]}
```

- packr 1.1: seg fault
- packr 1.2: seg fault
- packr from github/master: **Failed to find class: clojure.main**

So **on OS X** I can't confirm your observation that it works with an earlier version of packr.

But... I have some experimental code written in Rust which I had a similar problem with. It was just not able to find my Java main class. I "fixed" this by using a different approach to search for it, which I found here:

http://stackoverflow.com/questions/20328012/c-plugin-jni-java-classpath

Funny enough, my **Rust version of packr-mac** runs the clojure.main test above just fine...

So my conclusions for now:

- The method to pass the jar by "-Djava.class.path=", then search the main class with the invocation API seems "unfirm" at best. It doesn't seem to work at all with Clojure.
- If 1.1 runs for you, packr is still somehow inconsistent between Windows and OS X (and probably Linux too).

Regarding your application and Clojure, my best guess right now is that it misses classpath information, e.g. it can't find your main class, or something (clojure-1.6.0.jar?) your main class depends on.

**Comment by tommyettinger** [comment]
Ah, I was using the standalone jars (uberjars) generated by Leiningen (a build tool; the only way most Clojure developers build projects).  I have a project called [lein-packr](https://github.com/tommyettinger/lein-packr) that automates the downloading of JREs and calls Packr on an uberjar, and it currently works for 1.1 on windows -- I've generated an OSX build of an older game of mine (it's Packr 1.1 run on an uberjar, and uberjars should be runnable with `java -jar uber.jar`) and posted it [here](http://a.pomf.se/cvuxwy.zip).  If that .app (compressed to fit under pomf.se's 50 MB limit) doesn't work for you, @code-disaster , on Mac, there could be a number of things wrong, and I don't know what is most likely.  My lein-packr project at least works on Windows, but if it doesn't work on Mac/Linux it isn't doing what it should be...

**Comment by charactory** [comment]
I am experiencing this problem with packaging for Windows on OSX. It's a LibGDX application.

Here's the packr config:

```
{
    "platform": "windows",
    "jdk": "/Users/gancoline/Downloads/openjdk-1.7.0-u80-unofficial-windows-i586-image.zip",
    "executable": "Verbivore",
    "appjar": "/Users/gancoline/Dropbox/Projects/wordgame/desktop/build/libs/desktop-1.0.jar",
    "mainclass": "com/charactory/java/DesktopStarter",
    "vmargs": [
       "-Xmx1G"
    ],
    "resources": [
        "/Users/gancoline/Dropbox/Projects/wordgame/android/assets"
    ],
    "minimizejre": "soft",
    "outdir": "/Users/gancoline/Dropbox/Projects/wordgame/desktop/build/win/"
}
```

And here's the output of redirecting the executable to a file:

```
config file: C:\Users\kat1675\Documents\win/config.json
jar: C:\Users\kat1675\Documents\win/desktop-1.0.jar
mainClass: com/charactory/java/DesktopStarter
vmArg 0: -Xmx1G
```


I also removed the trailing spaces in the soft profile as mentioned by tommyettinger. I did crack open the jar and checked the entry class DesktopStarter was present. The jdk used is the unofficial JDK build at https://github.com/alexkasko/openjdk-unofficial-builds

**Comment by zackp30** [comment]
Is this a Clojure application, @charactory?

**Comment by charactory** [comment]
@zackp30 No Clojure, but it has Kotlin in it.

**Comment by zackp30** [comment]
To solve the problem we had to create a pure-java wrapper, which literally just calls the Clojure (or in your case Kotlin) API to call your main function from Java.

**Comment by so3arbelnox** [comment]
Also having this problem with Windows 64-bit. Tried both oracle JRE and open-jdk. Tried command line, with a .json file, and in code. The generated .exe does nothing but the JAR works fine. I tried piping output into a text file but no output. I am only using Java in my game.

**Comment by code-disaster** [comment]
With the latest version, you can use the command line interface with "--cli --console" to get output on Windows. See https://github.com/libgdx/packr/blob/master/src/main/native/README.md#command-line-interface for more.

**Comment by so3arbelnox** [comment]
Okay I switched to version 2.0 and was able to get output. Seems I was using an old version on Maven.

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
```
It stops after that. Clicking on the jar itself works fine. Wondering how else I can debug it.

**Comment by code-disaster** [comment]
Please try again with the "--verbose" parameter, so with "--cli --console --verbose".

There isn't much at this point which can go wrong without generating at least *some* error message. How's your config.json look like? Please note that with the new version, the main class name must use '.' as separator, not '/'.

**Comment by so3arbelnox** [comment]
Thank you that was a big help. I now can see the error, its failing to find the class. I am using '.' insteasd of '/' and it seems to be correct though. Should I not be pointing it to the DesktopLauncher class with the main method in it?

**Comment by code-disaster** [comment]
Yes, that's the idea. How's the verbose log output look like?

**Comment by so3arbelnox** [comment]
Here is what I get from the verbose log output.

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Adding 1 classpaths ...
  # Saedra's_Calling_v0.70.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener
Error: failed to load/find main class com.haftstudios.saedrascalling.desktop.DesktopLauncher
```

Here is my code if it helps.

```
// Build packr for Windows
Packr.Config config = new Packr.Config();
config.platform = Platform.windows64;
config.jdk = "C:\\Users\\Matt\\Downloads\\openjdk-1.7.0-u80-unofficial-windows-amd64-image.zip";
config.executable = "Saedras_Calling_v0.70";
config.mainClass = "com.haftstudios.saedrascalling.desktop.DesktopLauncher";
config.vmArgs = Arrays.asList("-Xmx1G");
config.classpath = Arrays.asList("C:\\Users\\Matt\\Downloads\\Saedra's_Calling_v0.70.jar");
config.resources = Arrays.asList("C:\\Users\\Matt\\workspace\\SaedrasCalling\\android\\assets\\");
config.outDir = "out-windows";
	    
try
{
   new Packr().pack(config);
}
catch (IOException exception)
{
   System.out.println("It didn't work: " + exception.getMessage());
}
```

Thanks for looking into it and apologies if I am doing something really stupid.

**Comment by badlogic** [comment]
You got an apostrophe in your jar files name. Pretty sure that makes it
explode.

**Comment by so3arbelnox** [comment]
Just tried removing that but have the same error as above. Also removed '.' and '_' for good measure as well.

**Comment by code-disaster** [comment]
"java.lang.NoClassDefFoundError: com/badlogic/gdx/ApplicationListener" very likely means that it found your application's main class, but failed to instantiate it because it misses other dependencies - core libGDX classes, so it seems.

I'm not sure though why it would work when run with "java -jar Saedra's_Calling_v0.70.jar" in your case.

**Comment by so3arbelnox** [comment]
Just fixed it! For some reason it was not working when I exported the JAR file with "Package required libraries into generated JAR". I changed it to "Extract required libraries into generated JAR" and it seems to work. Strange thing is both versions of the JAR run if I run them.

**Comment by smelc** [comment]
I ran into the same problem. To make clearer @so3arbelnox's fix, here's the story: when you build an executable standalone jar with Eclipse, if you select "Package required libraries into generated JAR" Eclipse *nests* the libraries jars into it, and adds a `jar-in-jar-loader.zip` jar to somehow be able to read their content. I believe packr-generated executables do not like that, so you need to _extract_ the library jars into your standalone jar, which is what Eclipse's "Extract required libraries ..." option does.
