### ISSUE TITLE
Problem on mac. NullPointerException

### ISSUE THREAD

**Issue by thkusch** [libgdx/packr#38]
Hello!

I'm trying to create a application on a mac machine. This is my json script:

{
    "platform": "mac",  
    "executable": "ElModConfig",
    "appjar": "ElModConfig.jar",
    "mainclass": "eu/elmod/elmodconfig/main/MainFrame",  
    "outdir": "out.mac"
}

I don't want to add a sdk explicitly, the application should use the installed one (works with jar bundler).
The output when calling java -jar packr.jar mac.json is:

Exception in thread "main" java.lang.NullPointerException
    at com.badlogicgames.packr.Packr.main(Packr.java:319)

any idea?

Thanks!
Thomas

**Comment by code-disaster** [comment]
> I don't want to add a sdk explicitly, the application should use the installed one

That's not supported. Both the packaging application and the native packr executable(s) expect a path to a JDK.

I've never used Jar Bundler, but judging by the description I'd ask: what do you still need packr for?

**Comment by thkusch** [comment]
Well, Jar bundler is not supported by Apple any more, it is limited to java 1.6 or lower and it doesn't support scripts. Your tool is great for creating multi platform bundles which is what I need. It's a pity that it cannot use installed JDKs as it bloats the package. Minimizing the JDK is not an option due to the X11-issue with OpenJDKs and legal stuff with Oracle's JDKs.
