### ISSUE TITLE
Antialiasing on Mac Retina

### ISSUE THREAD

**Issue by thkusch** [libgdx/packr#39]
When creating an application on a retina Mac, some kind of antialiasing is used. The text is blurry in comparison with the jar run natively (java -jar myapp.jar)
![bildschirmfoto 2015-04-09 um 10 25 49](https://cloud.githubusercontent.com/assets/11861274/7063043/6d4156ec-dea3-11e4-9e4f-38337c268d88.png)
![bildschirmfoto 2015-04-09 um 10 25 20](https://cloud.githubusercontent.com/assets/11861274/7063045/6f5ca6de-dea3-11e4-86f6-43c31fc2cc32.png)

**Comment by blair1618** [comment]
The newest versions of OS X detect whether an app is designed for rendering at retina resolutions using information from the app's Info.plist file. In the mac output from packr, find Info.plist and try adding this between the `<dict>` and `</dict>` tags:
```
<key>NSHighResolutionCapable</key>
<true/>
```

**Comment by KSDaemon** [comment]
Hi, @blair1618! Just tried your advice — no luck. 
<img width="325" alt="2015-08-11 21 02 21" src="https://cloud.githubusercontent.com/assets/458096/9205695/638ec906-406c-11e5-8fb4-bb74f448a586.png">

**Comment by KSDaemon** [comment]
Sorry for rapid answer, as i found in https://github.com/arduino/Arduino/issues/2309 — there is some OS cache, that need to be cleaned up for this to work.
