### ISSUE TITLE
Missing msvcp110.dll and msvcr110.dll on Windows.

### ISSUE THREAD

**Issue by titovmaxim** [libgdx/packr#41]
The generated .exe launcher produce an errors about missing msvcp110.dll and msvcr110.dll on some Windows installations. I think it is better to avoid such dependencies. There are two ways to solve it, First - put both files in the application folder.

Second (a better alternative in my opinion) is to link the launcher statically with them. The latter is achieved by using /MD key in Configuration Properties > C/C++ > Code Generation > Runtime Library according to:
http://stackoverflow.com/questions/21103532/msvcp110-dll-how-do-i-get-around-it

I'm using the latter one and it works with no problems. The reason I have not prepared a PR is that an icon is important in .exe. And to get the icon one should compile the .exe on it's own and do not use auto generated launcher.

**Comment by code-disaster** [comment]
That's odd, that's supposed to been fixed with https://github.com/libgdx/packr/commit/506f9061072c2647eebb18430b50ce7a9b28cad8

For the icons: what I did is to run a tool called ResHacker on the final Windows build to inject the application icon.

**Comment by titovmaxim** [comment]
@code-disaster. Thanks. Maybe my .exe was generated before this fix.
