### ISSUE TITLE
Windows 64bit support

### ISSUE THREAD

**Issue by Arcnor** [libgdx/packr#42]
Maybe my search skills are inexistent, but I can't find any issue about this.

Why there isn't any Windows 64bit version? I saw that @code-disaster submitted a build script that compiled it, but then removed it on a commit titled `Oops`...

Is there something missing to support this?

**Comment by Arcnor** [comment]
It will be nice to know the answer to this question before attempting anything myself, just in case it's a time waster :smile:.

**Comment by code-disaster** [comment]
I think I removed it because the change was accidental, and of no use yet because it would have required adjustments to Packr.java as well. That wasn't needed as Windows 64-bit is happily running 32-bit applications too.

**Comment by Arcnor** [comment]
Are those `Packr.java` changes big? I prefer to run the 64 bit version on Windows 64, specially because there is no server JRE for 32 bits (I'm always talking about the official Oracle one, not OpenJDK).

Thank you for your response!

**Comment by code-disaster** [comment]
No they aren't, just have a look what I did in [b7e8f10] (the one before my "oops" commit).

**Comment by Arcnor** [comment]
Seems very easy, yeah.

I'll try to find a Windows machine and compile this, will report back when/if I get it to work.

Thanks!

**Comment by code-disaster** [comment]
Windows 64 bit is now supported.

**Comment by littletinman** [comment]
New packr download coming soon?
