### ISSUE TITLE
Executables for Windows32 and Windows64 do not work

### ISSUE THREAD

**Issue by littletinman** [libgdx/packr#49]
Nothing happens after building and trying to run the executable in the output directly.

**Comment by littletinman** [comment]
This was due to my own user error. I had not noticed the change from "/" in the mainclass property to "." as a separator.

**Comment by littletinman** [comment]
So with further investigation on a windows 10 64 bit computer, nothing happens when you run the executable. Java is NOT installed on this testing machine. However, my machine which does have Java installed has no issues running the game.

**Comment by code-disaster** [comment]
Please try to run the executable with "-c -v --console". This should give you some output for troubleshooting.

**Comment by littletinman** [comment]
Failed to load VM... btw I noticed the instructions talk about a pom.xml but now where does it mention where to get such a pom.xml file.

**Comment by code-disaster** [comment]
Please show the full console output.

"Failed to load VM runtime library" means that jvm.dll could not be found or opened. Did you try to mix the 32-bit executable with a 64-bit JRE (or the other way around) by chance?

The pom.xml thingy can be ignored, it's just used as an example for the "resources" option.

**Comment by littletinman** [comment]
The full console output is exactly that:

"Failt to load VM runtime library"
Press Enter to exit


My platform settings look like the following:

"platform": "windows64",
"jdk": "/Users/Name/Documents/GitHub/Deployment/openjdk-1.7.0-u80-unofficial-windows-amd64-image.zip",

**Comment by littletinman** [comment]
Same happens with windows32 bit btw.

{
    "platform": "windows32",
    "jdk": "/Users/Phil/Documents/GitHub/Deployment/openjdk-1.7.0-u80-unofficial-windows-i586-image.zip",
    "executable": "gameName",
    "classpath": ["game.jar"],
    "mainclass": "com.philiproyer.gmae.desktop.DesktopLauncher",
    "vmargs": [
       "-Xmx1G"
    ],
    "minimizejre": "soft",
    "outdir": "Windows32"
}

**Comment by littletinman** [comment]
Further details, as mentioned above the guest machine has no Java SDK or JRE installed so it's a clean system. 

Am I wrong in understanding that the point of packr is to allow for this?

**Comment by code-disaster** [comment]
Yes, that's the whole point. Not sure what to advise here, besides maybe trying a different JRE version, or trying with minimize disabled.

Failing to load DLLs can have a lot of causes. I'll look into adding more detailed (Windows system) error messages for this case.

**Comment by littletinman** [comment]
I'll give disabling minification a try and report back.

**Comment by littletinman** [comment]
I should also mention that when running packr.jar I get the following warnings:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by littletinman** [comment]
Same problem unminified. 

"Starting JVM...."
"Failed to load VM runtime library"

**Comment by code-disaster** [comment]
As this happens on a clean system, I somehow suspect a missing dependency.

I wonder what happens if you replace the "jre/" folder with the full version from the OpenJDK zip file, then run "jre\bin\java -jar game.jar".

**Comment by littletinman** [comment]
Ok so I went ahead and installed a JRE from the oracle site and now i can run the jar but it instantly crashes stating "opengl is not supported by your graphics driver." Turns out the i3 intel integrated graphics drivers updated this summer don't seem to include opengl support. By upgrading to Windows 10 it upgraded the drivers and now no Libgdx games can run. 

Yay.....

So this is not an issue with Packr.

**Comment by littletinman** [comment]
Sorry to reopen but I narrowed down the issue.

**Machine Specs**
Intel i3-2330m Processor
Integrated Graphics Intel 3000
4 Gigs ram
Windows 10 64bit

I installed Java 1.8 and saw the same issue of saying OpenGL not supported.

Next uninstalled 1.8 and installed 1.7. I can now launch the app via the jar but running the .exe produces the "Failed to load VM runtime library".

At least for now I can give a hotfix for the few players experiencing this issue. Please let me know if you need any other info

**Comment by code-disaster** [comment]
For the "Failed to load VM runtime library" error, it'd be cool if you can try again with the latest version. I've added output for the Windows API GetLastError() function which might tell what it doesn't like exactly.

**Comment by littletinman** [comment]
Alright grabbed the latest, ran it, then ran the .exe with -c -v --console and got the following;

Loading JVM runtime library ...
Error code [126]: The specified module could not be found.
Error: failed to load VM runtime library!
Press ENTER key to exit.

**Comment by code-disaster** [comment]
Ok. Error code 126 can have different causes, unfortunately. Let me list all I know of, though some of them are rather unlikely in your case:

- jre\bin\server\jvm.dll not found relative to the working directory, which by default is the location of the packr executable
- tried to launch a 32-bit JRE from the 64-bit packr executable, or the other way around
- jvm.dll is missing some dependency, and fails to load for that reason

By your description I would vote for the last option, as you tried to run it on a freshly installed system. You'd probably need a tool like Dependency Walker or Process Monitor to find out the exact reason.

**Comment by littletinman** [comment]
SOLVED IT!

Ran Dependency Walker and it showed dozens of missing dlls. All of which are part of the Windows SDK. Downloaded and installed http://www.microsoft.com/en-us/download/details.aspx?id=8279 and problem solved!
