### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bigtunacan** [libgdx/packr#54]
When trying to run on Mac OS X (El Capitan) it errors out with the exception

    Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 15
        at com.badlogicgames.packr.Packr.parseArgs(Packr.java:429)
        at com.badlogicgames.packr.Packr.main(Packr.java:314)

The following is what I'm executing to package my application.

    java -jar ~/Downloads/packr.jar -platform-mac -jdk "https://bitbucket.org/alexkasko/openjdk-unofficial-builds/downloads/openjdk-1.7.0-u80-unofficial-macosx-x86_64-bundle.zip" -executable foo -classpath ["dist/frankenjar.jar"] -mainclass "JarMain" -vmargs "-Xmx1G" -minimizejre "soft" -outdir ./exe/

**Comment by code-disaster** [comment]
I suspect an error in your command line. E.g. you write "-platform-mac" which should be "-platform mac".
