### ISSUE TITLE
It doesn't show gui on windows 10 -> Issue with dependencies

### ISSUE THREAD

**Issue by jaimehrubiks** [libgdx/packr#59]
I can't get it to work now, I used to deploy this way last year and now I can not, maybe I am doing something wrong anyway.

My program runs, but the gui won't show up. It runs in background and I can see the process in the task manager and it even creates some folders so it is running, but nothing on screen. If I click on the .jar file it works perfect.

Last thing I did was to build latest fork from @code-disaster ( v2 sqash ), redownloaded openjdk and even updated .json files according to that specific fork branch, and same thing:

See a picture of my config
http://i.imgur.com/kGaZyzZ.png
(i also tried windows32 with the corresponding openjdk, version 45 and also version 80)
Thanks

**Comment by code-disaster** [comment]
Please note that my branch isn't widely tested yet. So far I tested with some small samples, and a build of our own Steam game. That said, if the JAR itself runs, it's unlikely that the new Java code to *create* the build did break anything.

What version of packr did you use before? The current master branch, or one before the native launcher rewrite?

**Comment by jaimehrubiks** [comment]
@code-disaster thanks and sorry for the delay.

I don't remember which version did I use in the past, though I have some records from 03/june/15

I just tried building latest build from libgdx and same thing happened. Also tested on other windows 10 and windows 7 pcs. Here is the config I used: http://i.imgur.com/VMIJs7V.png

I must be doing something wrong but I can't figure out what it is, sorry for that.

**Comment by code-disaster** [comment]
Please run the executable with "-c -v --console" parameters. This should show you some console output on Windows which might give a hint what's wrong.

**Comment by jaimehrubiks** [comment]
@code-disaster Ok that really helped me finding the cause of the issue.
Dependencies seem to be the issue here. I am using a java swing "look and feel" called WebLaf, and somehow I can't get it to work with packr.

I changed the way I am invoking the methods, I replaced the one I had with:

`UIManager.setLookAndFeel` ( "com.alee.laf.WebLookAndFeel" );

And now it started showing gui. However it still does not load dependencies, and no theme appears. It can't find the class of my ./lib folder and this message appears:

http://i.imgur.com/lmJzqcw.png

I am using same config as show above, is there anything I must do for /lib folder to be set on the classpath? Well.. I even tried packing my app and dependencies on same big .jar file and same thing happens.

It might not be fully related to packr, but it works in all cases executing with system java -jar, and even with attached jre/bin/java.exe...

Thanks again for your time, an advice is welcome and I'll keep testing.

**Comment by code-disaster** [comment]
Hm, that's odd indeed. Maybe java.exe does some additional classpath voodoo to discover your dependencies in the lib/ folder.

You can try adding your libs to the "classpath": [] section in config.json. In your case with WebLaf you probably need to list all the "lib/*.jar" files individually.
