### ISSUE TITLE
Error code [126]:

### ISSUE THREAD

**Issue by Utlaen** [libgdx/packr#60]
Hello,

Im getting "Error code [126]:" when running my jar with the windows32 generated .exe (jre1.8.0_92). I have tested it with the windows64 generated .exe, and manually running the jar with the copied JRE (and checked that is a 32 bits JRE) and works fine.

Testing on latest version of windows 10. Any help or hint would be welcome.

**Comment by Utlaen** [comment]
Found the problem... for some reason the 32 bit Java 8 JRE is missing the server/ (and jvm.dll) files... but they are in fact in the 32 bit Java 8 JDK /jre folder...

**Comment by Florianisme** [comment]
I still have this issue. I'm using the OpenJDK 11 64bit from here https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_windows-x64_bin.zip

I'm using "windows64" as the target platform and it still gives me this error, even though the jvm.dll ist definetly at the right location.
It is very unreliable, as it works perfectly fine on some 64bit machines but also fails to launch on other 64bit machines.
