### ISSUE TITLE
The OSX app got can't open

### ISSUE THREAD

**Issue by xirtam-ch** [libgdx/packr#61]
I got 
"you can't open the application because powerpc applications are no longer supported"
How can I do?

**Comment by code-disaster** [comment]
Very strange. There is no PowerPC version of the native executable. 

What version of packr do you use, and which MacOS version do you get this error on?

**Comment by xirtam-ch** [comment]
@code-disaster Thanks for reply.
I ues OSX 10.11.4 and packr is last version.
My step is 
1.I build the jar with gradle.
2.use the packr build the osx binary file.The binary file run normally.
3.Then I zip the files and rename to *.app,when I run the *.app I got this error ,is it my step wrong？

**Comment by code-disaster** [comment]
Yes, 3. is wrong and will lead to an invalid *.app bundle which OS X can't work with.

You need to run the packr utility, from command line or from Java code, as described at https://github.com/libgdx/packr#usage.

This will bundle the executable, your game JAR, any optional resources and the JRE in a folder structure which looks like this: https://github.com/libgdx/packr#output.

**Comment by xirtam-ch** [comment]
Thanks a lot :)
