### ISSUE TITLE
Error occurred during initialization of VM Unable to load ZIP library

### ISSUE THREAD

**Issue by scande3** [libgdx/packr#72]
Hiya! I've been upgrading from packr version 1.2 to 2.0 and using Java application code to handle my packing process. I am using a Windows 10 machine with with an official Oracle jdk1.8.0_92 release in to build my project in Android Studio. In packr 2.0, regardless of whether I build for Windows32 or Windows64 with appropriate JDK, running the generated exe file gives me the following output:

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx512m
Creating Java VM ...
Error occurred during initialization of VM
Unable to load ZIP library: C:\Users\Bluewolf\root\Android\gradleProjects\iCommand\release\out-windows2\jre\bin\zip.dll
```

The rest of this will be for the Windows64 example. The jdk I am using for that comes from: https://github.com/ojdkbuild/ojdkbuild (version java-1.8.0-openjdk-1.8.0.102-1-ojdkbuild.b14.windows.x86_64.zip). This github repo comes from going to the openjdk repo listed in the docs and clicking through to what they suggest to use now that they have discontinued their builds.

The "zip.dll" does indeed exist in the directory specified above.

My code to generate the build is essentially (similar to docs except the outDir requires a File handle rather than a String now as the docs specify):

```
    BasicConfigurator.configure();

    PackrConfig config = new PackrConfig();
    config.platform = PackrConfig.Platform.Windows64;
    config.jdk = "C:/Users/Bluewolf/root/Android/gradleProjects/iCommand/release/java-1.8.0-openjdk-1.8.0.102-1-ojdkbuild.b14.windows.x86_64.zip";
    config.executable = "iCommand";
    config.classpath = Arrays.asList("../desktop/build/libs/desktop-1.0.jar");
    config.mainClass = "com.bluewolf.iCommand.desktop.DesktopLauncher";
    config.vmArgs = Arrays.asList("Xmx512m");
    config.minimizeJre = "soft";

    File file = new File("C:/Users/Bluewolf/root/Android/gradleProjects/iCommand/release/out-windows2");
    config.outDir = file;

    try {
        new Packr().pack(config);
    } catch(Exception e) {
        System.out.println("PACKR ERROR OF: " + e.getMessage());
    }
```

Any ideas on what might be causing my issue or further information I could provide? Thanks!

**Comment by sheix** [comment]
Same with java-1.8.0-openjdk-1.8.0.111-1.b15.ojdkbuild.windows.x86_64. Did you found any solution/other jre?

**Comment by sheix** [comment]
@Tharkius I used another jdk - from [zulu](https://www.azul.com/downloads/zulu/) Don't know if it's good for everyone, but for me it was the alternative.

**Comment by Tharkius** [comment]
Yeah, actually trying out Zulu crossed my mind today. I'll try it out when I can.

Thanks for your time :)

**Comment by karlsabo** [comment]
If this is still an issue with the latest version of packr, please create a new issue with verbose output from packr included in the issue description.

Thanks.
