### ISSUE TITLE
Is Packr compatible with the IBM JDK?

### ISSUE THREAD

**Issue by kutuzof** [libgdx/packr#74]
For compatibility and licensing reasons I need to use the IBM JDK for a certain app. Is it possible to use packr in this case? Is it enough to zip /opt/ibm/..?

**Comment by code-disaster** [comment]
I don't think anyone ever tried that before, but packr itself doesn't assume much.

Your jdk zip must contain a **jre/** folder with the Java runtime. This is what's copied to the packr build.

The packr executable assumes a fixed path to the shared library it loads to spawn the JVM. For example, this is **jre/bin/server/jvm.dll** on Windows 64 bit.

**Comment by kutuzof** [comment]
In the IBM jdk (for Linux) the file is in **jre/lib/i386/client/libjvm.so** .

This fits with the error message I've been seeing. I suppose I could create a symlink in the expected location. 

Is this the only requirement from the executable?

**Comment by code-disaster** [comment]
This looks like a 32-bit JRE. Packr expects this at **jre/lib/i386/server/libjvm.so**. Which Java version is this JDK based on?

A symlink may work. Packr only tries to load and call this one library.

**Comment by karlsabo** [comment]
The latest version of packr supports OpenJDK 8, 11, and 14. Please try the latest version and create a new issue if you run into any problems.

**Comment by kutuzof** [comment]
> The latest version of packr supports OpenJDK 8, 11, and 14. Please try the latest version and create a new issue if you run into any problems.

Great! I'll give it a shot, thanks.
