### ISSUE TITLE
Problem with start app on Mac OS

### ISSUE THREAD

**Issue by lightway82** [libgdx/packr#75]
Hello,
I can't start my app from native starter program. My app start normaly by launch from terminal ./jre/bin/java -jar myapp.jar
If I launch native starter program from terminal then my app don't start

:~ develop$ /Users/develop/Documents/out-mac/Contents/MacOS/myapp ; exit;
Using bundle resource folder [1]: /Users/develop/Documents/out-mac/Contents/Resources/[myapp]
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Invoking static org.myapp.App.main() function ...
**Destroyed Java VM …**

**Comment by karlsabo** [comment]
Please try the latest version of packr, if you run into issues please create a new issue and paste the output of running packr in verbose mode.

Thanks
