### ISSUE TITLE
suggestion: use Proguard to keep only used parts of JRE

### ISSUE THREAD

**Issue by magicgoose** [libgdx/packr#77]
I think it's possible to use Proguard instead of hard-coded configs for minifying JRE.
It also can shorten(aka obfuscate) names of private classes, parameters, etc., further reducing the size.

https://stackoverflow.com/questions/2618176/is-it-possible-to-shrink-rt-jar-with-proguard

**Comment by magicgoose** [comment]
NB: this might be prohibited practice to redistribute the result if it was from Oracle (Sun) JRE, but maybe this would be fine for OpenJDK.

**Comment by karlsabo** [comment]
With the new Java module system and jlink I don't think this feature makes sense anymore. Closing this issue.
