### ISSUE TITLE
"NoClassDefFoundError" on MacOS

### ISSUE THREAD

**Issue by exmapleDotJpg** [libgdx/packr#78]
hey guys,
i tried to use packr to pack an app for MacOS including a JRE. the packing process seems to work nicely, but i can't open the app. it always gives me:

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/sun/media/sound/JDK13Services
at javax.sound.sampled.AudioSystem.getProviders(AudioSystem.java:1629)
at javax.sound.sampled.AudioSystem.getAudioFileReaders(AudioSystem.java:1404)
at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1105)
at Audio.AudioPlayer.<init>(AudioPlayer.java:11)
.........

The .jar itself works flawlessly when i run it with my computer's own java. Also i tried every JDK build i could find and it gives me the same error every time. Since the problem seems to be related to audio I/O, i also tried using a different audio library, with no effect.

My config file:

{
    "platform": "mac",
    "jdk": "/Users/.../bounces/openjdk-1.7.0-u45-unofficial-icedtea-2.4.3-macosx-x86_64-image.zip",
"executable": "Moths",
"classpath": [
    "/Users/.../bounces/Moths_JRE_1.7_beadz.jar"
],
"mainclass": "Main.Game",
"vmargs": [

],
"resources": [

],
"minimizejre": "soft",
"output": "/Users/.../bounces/Moths.beadz.app",
"icon": "/Users/.../bounces/icon.icns"
    }

Any ideas?

**Comment by code-disaster** [comment]
As this seems to fail very late, there might be an issue with the OpenJDK version you use and these Audio classes.  Does it work if you run the JAR using the bundled JRE, e.g. with `./jre/bin/java -jar Moths_JRE_1.7_beadz.jar` ?

**Comment by exmapleDotJpg** [comment]
Good idea. Tried it, same error. This really points into the direction of the JDK being the problem rather than packr, doesn't it?
i tried numerous OpenJDK versions from 1.6** to 1.7**, compiling my program compliant to the target JDK. The same error occurs with every one of them.

I've never had this kind of Exception before, so i'm not sure what it means, but according to its name there is some class file that can't be found - however the com/sun/media/sound/JDK13Services.class IS part of all the OpenJDK's i tried! Any other ideas? many thanks in advance

**Comment by code-disaster** [comment]
I just realized that you are using the soft minimize profile. `com.sun.media` is one of the [packages](https://github.com/libgdx/packr/blob/master/src/main/resources/minimize/soft#L8) which are deleted by that.

**Comment by exmapleDotJpg** [comment]
Ah, that was it. Thank you very much!

**Comment by exmapleDotJpg** [comment]
Oh, sorry to reopen. Now i got a related issue. My application uses some libraries for .mp3 files (jl, mp3spi, tritonus_share). When i run the .jar (with the same JRE i'm packing into the app bundle), everything works neatly.
the application made by packer, however, produces this exception here whenever an mp3 should be loaded:

javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
	at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1155)
	at Audio.AudioPlayer.<init>(AudioPlayer.java:21)
	at GameState.MenuState.<init>(MenuState.java:45)

sound files with formats that are natively supported by javax, such as .wav, don't cause any problems, so I assume that,  although they ARE there, the app bundle doesn't use the mp3 libraries? Any clues on this?

**Comment by code-disaster** [comment]
Can you try to merge #73 (or simply download [the binary from that branch](https://github.com/revaultch/packr/blob/parent_and_context_class_loader/src/main/resources/packr-mac)), then replacing your executable with `packr-mac`? I wonder if this is related to your issue, because it looks like javax.sound uses the classloader to search for available sound providers.

**Comment by exmapleDotJpg** [comment]
Yes, this did the trick! Thank you. Just out of curiosity, what was the issue and how does the alternative executable fix it?

**Comment by code-disaster** [comment]
It changes how the class loader is configured which is then used to load the JAR file, and also updates the current thread (the main thread) to use this class loader in case the runtime tries to load more classes later on. At least this is how I understand it, @ukeller did the PR.
