### ISSUE TITLE
Using Packr 2.0 With JavaFX Kills Executable Before Running

### ISSUE THREAD

**Issue by SoupFX** [libgdx/packr#81]
Hello. In the latest version of Packr (2.0), creating a executable for a JavaFX application for Windows seems to not work.

``` java
public static void main(String[] args) {
        System.out.println("Test 1");
            Application.launch(App.class, args);
            System.out.println("Test 2");
        System.out.println("Test 3");
    }
```

In the above code, only "Test 1" gets outputted and it never reaches "Test 2". The program will exit.

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx512m
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
Invoking static App.main() function ...
Test 1
Destroyed Java VM ...


This wasn't an issue in the older version of Packr
```

**Comment by code-disaster** [comment]
Which "older version of Packr" did work for you? Also, which JRE are you bundling?

I did a brief test with a simple JavaFX app created by IntelliJ, and while it works fine bundled with a Oracle 8 JRE, it fails with a NoClassDefFoundError when bundled with a Zulu JRE.

**Comment by SoupFX** [comment]
@code-disaster Oh I was bundling a Zulu JRE. I assumed it worked with an older version of packr but it might have been the bundled JRE.

I tried catching for exceptions with the bundled Windows Zulu JRE but there was no exceptions that were caught. I tried the soft minimize profile.

**Comment by code-disaster** [comment]
The Zulu JRE I'm looking at here right now (zulu8.15.0.1-jdk8.0.92-win_x64) doesn't seem to ship with any JavaFX classes. So I'm slightly confused now. :)

**Comment by karlsabo** [comment]
Hey @SoupFX, if you're still using packr, please try the latest version and open a new issue if you run into any problems, thanks.
