### ISSUE TITLE
OSX app not fully functional

### ISSUE THREAD

**Issue by kcpeppe** [libgdx/packr#85]
Packaged a desktop app using JFreeChart. The app starts and all of the windows are functional but the JFreeChart scatter plots do not build and thus those windows are blank.

**Comment by code-disaster** [comment]
I suspect a classpath or JRE minimize issue. Please run with "<executable> --cli --verbose" from a terminal and look out for error messages.

**Comment by kcpeppe** [comment]
Once I started building without -minimizejre soft the problem seems to have gone away. I'm going to close this issue.
