### ISSUE TITLE
SLF4J configuration

### ISSUE THREAD

**Issue by kcpeppe** [libgdx/packr#86]
packr>java -classpath slf4j-1.7.21\slf4j-simple.jar -jar packr.jar  ......

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Attempts to configure with other jars have also failed on both Windows and OSX

**Comment by code-disaster** [comment]
You can't mix `-classpath` and `-jar`.

`java -classpath slf4j-1.7.21\slf4j-simple.jar;packr.jar com.badlogicgames.packr.Packr`

**Comment by 3xp0n3nt** [comment]
Changing the semicolon to a colon for classpath separation allowed this to work for me.

**Comment by code-disaster** [comment]
Yes, it's ':' on Linux/MacOS. FYI, slf4j is a dependency of org.zeroturnaround.zt-zip. We could add a logger as a dependency to get rid of the warning, but this would pollute environments which embed packr as library themselves. They might use slf4j and register a logger themselves already.

**Comment by code-disaster** [comment]
Actually, never mind. TIL a Maven feature which [just works](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html)... 👍
