### ISSUE TITLE
Windows Executable fails silently

### ISSUE THREAD

**Issue by kcpeppe** [libgdx/packr#87]
built windows executable which starts but then immediately exits with no warnings or error messages

**Comment by code-disaster** [comment]
Please run with "<executable> --cli **--console** --verbose" from a terminal, it may show you some meaningful output.

**Comment by kcpeppe** [comment]
I have done so and I've gotten the error message
Error code [126]: The specified module could not be found
Error: failed to load VM runtime library!

**Comment by code-disaster** [comment]
This may be a duplicate of #82. To test this, you can try copying msvcr100.dll from the bundled jre/bin folder next to the packr executable.

**Comment by kcpeppe** [comment]
close and move issue to #82
