### ISSUE TITLE
Incorrect ClassLoader URL on OS X Causes Classpath Scraping Issues

### ISSUE THREAD

**Issue by 3xp0n3nt** [libgdx/packr#88]
Let's say I have an app I created with the latest version of packr called `myApp`. I can run `myApp.app` & `myApp.app/Contents/MacOs/myApp` just fine.

As part of this app's functionality, it scrapes the classpath to get a list of class files from certain packages within the jar. This functionality works fine when running the executable jar directly, and not the packr-created native executables.

After many hours of testing and research, I discovered that the classpath URL is actually incorrect (or incomplete) when running the packr-created native app. Here are my findings:

Output of:

`System.out.println(((URLClassLoader)ClassLoader.getSystemClassLoader()).getURLs());`

when running **myApp.jar** directly:

`[file:/.../myApp.app/Contents/Resources/myApp.jar]` <= Perfect, works great.

when running **myApp.app**:

`[file:/.../myApp.app/Contents/Resources/]` <= Huh? This works for the bundled JRE classes because they're unpacked into `Resources/jre`, but this does **NOT** work for `myApp.jar` classpath. It seems there should be two URL's in this case:

Desired output:

`[file:/.../myApp.app/Contents/Resources/, file:/.../myApp.app/Contents/Resources/myApp.jar]` <= This would work!

As it is, when I scrape the classpath of myApp as created by packr, I'm only getting JRE classes.

I've been hacking on `packr.cpp` for a while now, trying to track down this nefarious bug.

FWIW, here's my packr JSON configuration:

```
{
  "platform": "mac",
  "jdk": "/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home",
  "executable": "myApp",
  "classpath": [
    "myApp.jar"
  ],
  "mainclass": "com.example.myapp.main",
  "vmargs": [
    "Xmx1G"
  ],
  "resources": [
    "res",
  ],
  "minimizejre": "oraclejre8",
  "output": "out/myApp.app"
}
```

P.S. FYI It was a huge pain to build packr's native executables following [native/README.md](https://github.com/libgdx/packr/blob/master/src/main/native/README.md), as one small-but-critical detail was left out: On OS X, fips doesn't add the necessary `-stdlib=libc++` flag to `CMAKE_CXX_FLAGS` in `src/main/native/fips/cmake-toolchains/osx.cmake` when compiling with Apple/Xcode/LLVM/clang toolchain, which means C++11 support is missing by default (?!) Anyway, this would have been very useful to know, when trying to understand why `#include <functional>` was broken in `packr.h` (among other things).

**Comment by 3xp0n3nt** [comment]
It seems misleading to internally adjust the classpath to the parent directory of the executable JAR. When I specify `classpath: ["myApp.jar"]`, I'm expecting that eventually you're native code is going to invoke `java -cp myApp.jar;...` You can **add** `myApp.app/Contents/Resources/` to the classpath, that would be way more straightforward. I understand that myApp.app/Contents/Resources/` *includes* `myApp.jar`, but that doesn't **fully** work in all cases, as you can see above. It **is** sufficient to simply *run* the application, however. I'm also sure you were just not able to test this use case, and that it was not intentionally overlooked. But a fix, or at least giving some hints about a fix, would be greatly appreciated!

I read all this, including the links, didn't really help though.

```
	//! Method to retrieve 'static void main(String[] args)' from a user-defined class path.
	//! The original 'packr' passes "-Djava.class.path=<path-to-jar>" as an argument during
	//! initialization of the JVM. For some reason this didn't work for me on *some* systems.
	//!
	//! This method uses JNI voodoo to get the thread context classloader, construct a file
	//! URL, point it to the user JAR, then use the classloader to load the application class'
	//! static main() method.
	//!
	//! References:
	//! http://stackoverflow.com/questions/20328012/c-plugin-jni-java-classpath
	//! http://www.java-gaming.org/index.php/topic,6516.0
```

I don't know enough about "JNI voodoo". 😅

**Comment by code-disaster** [comment]
> I don't know enough about "JNI voodoo". 😅

The comments inside this method may be helpful. They describe which equivalent of Java code the JNI calls actually try to do.

> System.out.println(((URLClassLoader)ClassLoader.getSystemClassLoader()).getURLs());

Please try with `Thread.currentThread().getContextClassLoader()` instead. This is where packr registers the classpath, which is a list of URLs for the .jar files picked from config.json.

> -stdlib=libc++

This is odd. Believe me or not, I don't hack my local copy of the repository to get the compile working. Which means, it compiles here out of the box, and it has been since I changed the build to use fips. How do you call the build exactly, via ./fips command line or the ./build-macos.sh script? Also, what OS X and Xcode versions are you running?

**Comment by 3xp0n3nt** [comment]
Thank you for the fast response, much appreciated!

> Please try with Thread.currentThread().getContextClassLoader() instead. This is where packr registers the classpath, which is a list of URLs for the .jar files picked from config.json.

It's working! Thank you! Can you add a note in the README about this gotcha? I wouldn't wish the pain of this issue on my worst enemies... 😅 

> This is odd. Believe me or not, I don't hack my local copy of the repository to get the compile working. Which means, it compiles here out of the box, and it has been since I changed the build to use fips. How do you call the build exactly, via ./fips command line or the ./build-macos.sh script? Also, what OS X and Xcode versions are you running?

OS X 10.12.1 (Sierra)
Xcode 8.1 (8B62)

First build only:

```
cd <packr-project-dir>/src/main/native/packr
./fips
./fips fetch
cd ../fips/cmake-toolchains/osx.cmake
vim osx.cmake
<insert -stdlib=libc++ in CMAKE_CXX_FLAGS, directly after -std=c++11, L53>
<Save & quit osx.cmake>
```

First AND subsequent builds:

```
cd <packr-project-dir>/src/main/native/packr
mkdir build
cd build
cmake ..
make
cd ..
./build-macos.sh

cd ../../../..
mvn clean package
cp -f target/packr-2.0-SNAPSHOT-jar-with-dependencies.jar <my-project-dir>/packr/packr.jar
```

**Comment by 3xp0n3nt** [comment]
`clang -v` gives:

```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by code-disaster** [comment]
```
cd <packr-project-dir>/src/main/native/packr
mkdir build
cd build
cmake ..
make
cd ..
./build-macos.sh
```

To be honest, I don't understand this extra cmake step. All I do is:

```
cd <packr-project-dir>/src/main/native/packr
./build-macos.sh
```

... which should be really the same as

```
cd <packr-project-dir>/src/main/native/packr
./fips set config packr-osx-xcode-release
./fips clean && ./fips build
```

... where `packr-osx-xcode-release` is just a copy of fips' normal osx-xcode-release config plus FIPS_OSX_UNIVERSAL defined.

I'm also on Sierra / Apple LLVM 8.0.0.

**Comment by 3xp0n3nt** [comment]
> To be honest, I don't understand this extra cmake step. All I do is:
>
> `cd <packr-project-dir>/src/main/native/packr`
> `./build-macos.sh`

Thanks for this. I'm not familiar with fips, so it wasn't obvious to me that it was redundant. The missing `-stdlib=libc++` really threw me for a loop and so I was really digging into cmake and fips configuration, which is probably where the unnecessary complexity creeped in.

> This is odd. Believe me or not, I don't hack my local copy of the repository to get the compile working. Which means, it compiles here out of the box, and it has been since I changed the build to use fips.

I really don't know, and I haven't been able to justify the time to dig into it. The only idea I had was that after upgrading recently to Sierra, I hadn't yet installed the Xcode command line tools. I always forget to do that, since I don't really use Xcode. This has caused other issues in the past, and I'm still not sure why it's not automatic, other than having to accept a license agreement.

**Comment by 3xp0n3nt** [comment]
> -stdlib=libc++

Since I'm on a roll tonight hacking on packr, I went ahead and did a clean master checkout of the source, ensuring all auto-generated fips and cmake files were gone, and re-built the native executables per your advice. No errors.

This simply confirms to me that the errors were caused by not installing the Xcode command line tools (by opening Xcode on Sierra for the first time).

Maybe we could add a note about this in the README. Hopefully it will save someone ~hours of time~ a few moments. 😅

**Comment by 3xp0n3nt** [comment]
> This simply confirms to me that the errors were caused by not installing the Xcode command line tools (by opening Xcode on Sierra for the first time).

I stand corrected. I was still suspicious, so I tried building the native executables the wrong way, as I did before:

```
cd <packr-project-dir>/src/main/native/packr
mkdir build
cd build
cmake ..
make
cd ..
./build-macos.sh
```

Still got the same errors, with C++11 code not being recognized. 🙈 

Apple 1, me 0.
