### ISSUE TITLE
Not a valid Windows 32 executable

### ISSUE THREAD

**Issue by mxmlbernard** [libgdx/packr#91]
Hi,

When using packr to package a windows32 app and using it on windows XP SP3, it does not work and tells me it's not a valid win32 application.

I checked the .exe properties, and the minimal windows version is set to 6 which corresponds to Vista (5.1 for XP).
I checked jdm.dll from the JRE in case of, and it's set to 5.1 so no problem here.

Is there a workaround to package an app (I use libgdx) for windows XP ?

**Comment by code-disaster** [comment]
It probably changed with this commit: fea49d71d2418da5b51d5b3de85ef24284ba1274, so one workaround  may be to build a version yourself with some revision before that.

**Comment by d6e** [comment]
I am also getting this same error. I tried building a version before `fea49d7` (specifically `f23a3fb`) as you suggested and still get the same "Not a valid Win32 executable" error. Any suggestions?

**Comment by karlsabo** [comment]
Packr no longer built for 32-bit Windows. Closing this issue.
