### ISSUE TITLE
Windows: Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by andrea-marini** [libgdx/packr#93]
I'm trying packaging a jar on windows 7 64 (also tried windows XP) with the following parameters:

java -jar packr.jar --jdk openjdk-1.7.0-u80-unofficial-windows-i586-image.zip --executable myApp --classpath myapp.jar --mainclass it.test.myapp.Main --vmargs Xmx1G --minimizejre soft --output "C:\Users\user\Desktop\output\"

and I'm returned no matter what the error:

Cleaning output directory 'C:\Users\user\Desktop\output' ...
Exception in thread "main" java.lang.NullPointerException
        at com.badlogicgames.packr.Packr.copyExecutableAndClasspath(Packr.java:1
24)
        at com.badlogicgames.packr.Packr.pack(Packr.java:55)
        at com.badlogicgames.packr.Packr.main(Packr.java:308)

**Comment by code-disaster** [comment]
Yeah, seems it still lacks some command line validation checks. In your case, you missed the ```--platform``` parameter.

**Comment by andrea-marini** [comment]
I had seen --platform floating around but thought it was no longer needed, now however I get errors when the program tries to delete tmp directories:

Copying executable ...
Copying classpath(s) ...
Unpacking JRE ...
Copying resources ...
Minimizing JRE ...
Removing foreign platform libs ...
java.io.IOException: Unable to delete directory C:\Users\user\Desktop\packr_
output\app.jar.tmp\org\neo4j\cypher\internal\frontend\v3_0.
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:981)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1381)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1044)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:977)
        at com.badlogicgames.packr.PackrReduce.removePlatformLibs(PackrReduce.ja
va:247)
        at com.badlogicgames.packr.Packr.pack(Packr.java:65)
        at com.badlogicgames.packr.Packr.main(Packr.java:308)

**Comment by code-disaster** [comment]
It's difficult to tell w/o debugging, but I suspect the crash is caused by one of Window's infamous file access / permission / lock "features".

As for the second try, no idea. Maybe adding the `--verbose` parameter gives more information. The output (on Windows) isn't a single executable, but a folder structure as described [here](https://github.com/libgdx/packr#output).

**Comment by andrea-marini** [comment]
I tried with --verbose option, now it works flawlessly creating the directory structure as you said (hoped all could be embedded in the .exe actually but nevertheless), below the result

> java -jar packr.jar --platform windows64 --jdk openjdk-1.7.0-u80-unofficial-windows-i586-image.zip --executable myApp --classpath myApp.jar --mainclass it.test.myapp.Main --vmargs Xmx1G --minimizejre soft --verbose --output C:\Users\user\Desktop\output\
> Cleaning output directory 'C:\Users\user\Desktop\output' ...
> Copying executable ...
> Copying classpath(s) ...
> Unpacking JRE ...
> Copying resources ...
> Minimizing JRE ...
>    Removing files and directories in profile 'soft' ...
>    Unpacking 'C:\Users\user\Desktop\output\jre\lib\rt.jar' ...
>    Repacking 'C:\Users\user\Desktop\output\jre\lib\rt.jar' ...
>    56215 kb -> 25134 kb
>    No file or directory 'C:\Users\user\Desktop\output\jre\lib\rhino.jar' found
>    Removing 'C:\Users\user\Desktop\output\jre\bin\java-rmi.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\java.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\javaw.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\keytool.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\kinit.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\klist.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\ktab.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\orbd.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\pack200.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\policytool.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\rmid.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\rmiregistry.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\servertool.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\tnameserv.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\unpack200.exe'
>    Removing 'C:\Users\user\Desktop\output\jre\bin\client'
> Removing foreign platform libs ...
>    Unpacking 'myApp.jar' ...
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-atk-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-awt-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-cairo-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-glx-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-gnome-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-mozilla-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-pi-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-pi3-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-webkit-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-xpcominit-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-xulrunner-fix.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\libswt-xulrunner-gtk-4332.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\META-INF\native\libnetty-transport-native-epoll.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\META-INF\native\linux32\libjansi.so'
>    Removing 'C:\Users\user\Desktop\output\myApp.jar.tmp\META-INF\native\linux64\libjansi.so'
>    Repacking 'myApp.jar' ...
>    105192 kb -> 104690 kb
> Done!
> 

when I execute myapp.exe howver I get a crash error and the windows details as below:

> Firma problema:
>   Nome evento problema:	APPCRASH
>   Nome applicazione:	myapp.exe
>   Versione applicazione:	0.0.0.0
>   Timestamp applicazione:	5841340c
>   Nome modulo con errori:	myapp.exe
>   Versione modulo con errori:	0.0.0.0
>   Timestamp modulo con errori:	5841340c
>   Codice eccezione:	c0000005
>   Offset eccezione:	000000000000410e
>   Versione SO:	6.1.7600.2.0.0.256.49
>   ID impostazioni locali:	1040
>   Informazioni aggiuntive 1:	d070
>   Ulteriori informazioni 2:	d07006194d9a3ac80daa0485098b036f
>   Ulteriori informazioni 3:	09e7
>   Ulteriori informazioni 4:	09e73841bd27f12a27b059f968cb9617
> 
> 
>

**Comment by code-disaster** [comment]
You build for 64-bit (`--platform windows64`), but bundle a 32-bit Java runtime (`openjdk-1.7.0-u80-unofficial-windows-i586-image.zip`). This doesn't work, the executable and JRE versions must match their architecture type.

One word of warning: I've seen people having issues with this 1.7.0-u80 build before, so in case it still doesn't work, you should try a different JRE. For example, we shipped our last game with 1.7.0-u45 on all three platforms.

**Comment by andrea-marini** [comment]
> You build for 64-bit (--platform windows64), but bundle a 32-bit Java runtime (openjdk-1.7.0-u80-unofficial-windows-i586-image.zip). This doesn't work,

sorry I got in a compile frenzy and overlooked the platform, now it correctly creates an .exe which correctly launches my jar.

Two questions however:

1. why does it complain about missing MSVCR100.dll just before launching java? it seems related to the C++ Redistributable Package 2010, is it a bug?
2. does packr permit to embed the jre/ folder and myApp.jar all inside an exe? (that was my initial understanding of the program)

**Comment by code-disaster** [comment]
1. this is supposed to be fixed, see #82.
2. no, that's never been the case with packr

**Comment by andrea-marini** [comment]
1. ok copied the msvcr100.dll right next to the myApp.exe and now works flawlessly
2. pity, would have been exactly what I dreamed of, an exe containing everything needed to run a java program

thank you
