### ISSUE TITLE
Remove Console logging 

### ISSUE THREAD

**Issue by joaquinrinaudo-olx** [libgdx/packr#96]
Hello,

Is there a way to remove the console logging done when executing the file? such as:

```
Loading JVM runtime library ...
Passing VM options ...
  # -Xmx1G
Creating Java VM ...
Passing command line arguments ...
Loading JAR file ...
```
Thanks!

**Comment by joaquinrinaudo-olx** [comment]
Hi, thanks for the feature. Is Is the binary updated with the latest changes?

**Comment by code-disaster** [comment]
You are right, I didn't update the binaries. I just pushed new versions, so they should be included in the next snapshot/download as soon as the build server has done its thing.
