### ISSUE TITLE
"openjdk-unofficial-builds" is discontinued.

### ISSUE THREAD

**Issue by ghost** [libgdx/packr#97]
https://github.com/alexkasko/openjdk-unofficial-builds

The above linked repo is discontinued and the new repo they link to doesn't provide any mac archives. Please direct us to other sources of the JRE.

**Comment by SolarLune** [comment]
I dunno if you still need this info, but you can find 64-bit JDK builds over at [Azul](http://www.azul.com/downloads/zulu/), and you should be able to package [Oracle's JREs](http://www.oracle.com/technetwork/java/javase/downloads/index.html) just fine.
