### ISSUE TITLE
The ReadMe refers to Packr 2.0 but 1.2 appears to be latest

### ISSUE THREAD

**Issue by william-ferguson-au** [libgdx/packr#99]
At least it's the latest on Maven Central.

Am I missing something?

**Comment by code-disaster** [comment]
That's because there has been no *release* since 1.2. New builds are available as [snapshots](https://oss.sonatype.org/content/repositories/snapshots/com/badlogicgames/packr/packr/), or as [download](http://bit.ly/packrgdx).

**Comment by karlsabo** [comment]
The latest version can be downloaded from GitHub, for Maven repositories please see the readme file.
